### ISSUE TITLE
Force rebuild / redeploy

### ISSUE THREAD

**Issue by datosh** [windmilleng/tilt#1012]
Hey,

I am trying to use tilt in my current environment:
Windows 10 host machine using WSL to run Ubuntu 18.04.
Everything works great so far, only feature that is buggy is the file watch, and auto build+deploy. This seems to be [known issue with WSL](https://github.com/Microsoft/WSL/issues/216) not fully implementing inotify. There is also [more related information in VS Code Repo](https://github.com/Microsoft/vscode/issues/53621).

I don't think this is something tilt can (or should) solve, but in order to still use tilt features in an environment that does not support it would be nice to have a force rebuild & deploy in the HUD, just like <spacebar> can be used to manually to a rebuild (for changed) components, it would be nice to have a force rebuild shortcut as well!

Any thoughts / ideas appreciated!
Cheers,
Datosh

**Comment by nicks** [comment]
Oof, that's good to know.

I can think of a few different ways to fix this.

One would be to use a polling filewatcher like the WSL issue suggests. This is slow, but would work.

Another would be to add a key like <spacebar> to force rebuild + deploy. This would be easy to do, and something we should probably do anyway, though you'd miss out on some of the incremental build optimizations, because Tilt wouldn't know what's changed.

Question: why are you using WSL? I'm asking because we're also trying to figure out how to prioritize native Windows support. If you'd rather have Tilt on Windows than a subpar Tilt on WSL experience, that'd be good to know!

**Comment by datosh** [comment]
Thanks for the quick feedback! 
I'm using WSL, since most of the tools are native to Linux, and I'm forced to work in a Windows environment. WSL works better than using a VM (only in some ways) since you do not have the additional virtualization layer. For example it's easier to spawn a virtual machine from Ubuntu running in WSL, than Ubuntu running in (e.g.) Virtual Box, since you do not have to forward the virtualization capabilities. Some tools do not even support the forwarding!

Yeah so bottom line: I prefer better WSL support over Windows support, but I think other people have different needs. And, as already stated, it works like a charm, aside from the file watch problem, which is ultimately a WSL bug.

**Comment by jazzdan** [comment]
@nicks is this issue resolved with the `--auto-deploy` flag of `tilt up`?

**Comment by nicks** [comment]
@jazzdan no, that doesn't work for this use-case because it still relies on filechange events to do things

**Comment by maiamcc** [comment]
@datosh, I don't know if you're still interested in this, but for what it's worth, we've [spec'd out a possible solution](https://github.com/windmilleng/tilt.specs/blob/master/manual_update_control.md). TBD when we're going to start implementing, but just wanted to let you know that it's still on our radar.

**Comment by datosh** [comment]
@maiamcc, thanks for the update :) 
I have read the proposed solution, and I think this is heading in the right direction.
In the spec you talk quite a bit about changes to the UI, do you also consider CLI changes? This might be helpful for things like editor / IDE integration. Is this in focus of Tilt?
I think it would be nice to use the build/deploy capabilities of, e.g., VS Code, or even write a simple Tilt plugin to make it a first class citizen in VS Code? No necessarily right now, but keeping the options open.

**Comment by maiamcc** [comment]
@datosh yeah, I think that's a possibility, but pretty far in the future for us. Still, it's definitely crossed our minds (it's on [our roadmap](https://github.com/windmilleng/tilt/blob/master/ROADMAP.md#vscode-integration-p2-c2) for later) -- glad to hear that other people are interested in this, it's useful data!

**Comment by MattHodge** [comment]
An example issue I had where a way to force a rebuild would be useful:

* I make a change and am building / pushing an image. My ECR token times out, causing the push to fail and Tilt to show the error.
* Without another code change, I cannot "retry" the build after I login to ECR.

**Comment by maiamcc** [comment]
Hey folks, I've just shipped [Force Update]I(https://blog.tilt.dev/2019/11/14/force-update.html) -- take a look and let us know if this meets your needs, and feel free to drop us a line/open another issue if there's big functionality missing, or ways you think we can improve it :)
