### ISSUE TITLE
Make tilt stay on the same kubernetes context

### ISSUE THREAD

**Issue by thrawny** [windmilleng/tilt#1046]
If you run `tilt up` and then switch kubernetes context in another terminal session then tilt will start working in that context instead. This is somewhat scary as I did `tilt up` and then switched to our production context and was looking at things there, having forgotten that tilt was still running.

Can we make tilt definitely stay on the same context, or pass in the context we want to use as an argument to tilt up? What do you think? I would be happy to contribute if you think it is a good idea.

I know I could use the `KUBECONFIG` environment variable as a workaround. Maybe alias tilt like so:

```
alias tilt="KUBECONFIG=/path/to/devcfg/ tilt"
```

But I think it would be nice if this was supported natively.

**Comment by jazzdan** [comment]
@thrawny I'm going to close this but feel free to re-open if you think there's more work to be done!
