### ISSUE TITLE
oneup tutorial errors when pushing docker image

### ISSUE THREAD

**Issue by adamdecaf** [windmilleng/tilt#1056]
After pulling down the [latest tilt source](https://github.com/windmilleng/tilt/tree/master/integration/oneup) I ran `tilt up` from `integration/oneup`, but ran into a problem when tilt tries to push the docker image. I don't have that auth config file to push.

<img width="1232" alt="screen shot 2019-01-21 at 10 11 49 am" src="https://user-images.githubusercontent.com/120951/51492131-8e6e3380-1d65-11e9-8037-7324cfca300c.png">

**Comment by nicks** [comment]
This usually means that you don't have kubectl configured to talk to a local cluster, like Docker For Mac or Minikube. Can you check out the FAQ and see if that resolves your problem?
https://docs.tilt.build/faq.html#q-i-m-getting-push-errors-like-unauthorized-you-don-t-have-the-needed-permissions-when-i-try-to-build-the-first-example-what-do-i-do

**Comment by adamdecaf** [comment]
Ah. My bad, thanks!
