### ISSUE TITLE
tilt up gives: No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by nabadger** [windmilleng/tilt#1081]
Hey 

As per subject, I just ran into this issue:
```
>> tilt up
Error: No Auth Provider found for name "oidc"
```

My local kubeconfig has my user configured to use an OIDC auth provider.

I think this is usually resolved by importing the following:

```
import (
     _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
```
I'm not sure where the error is coming from, maybe `./k8s/portforward.go` (there's some related gcp auth support there).

Thanks

**Comment by nicks** [comment]
yep, you're right! we need to install some plugins. should be a quick fix, one sec
