### ISSUE TITLE
Support "app parameters"

### ISSUE THREAD

**Issue by hausdorff** [windmilleng/tilt#1104]
It would be nice to do something like: `tilt config set registryName hausdorff` and then be able to reference `registryName` throughout the `Tiltfile`. This would really cut down on the number of caveats the demo has.

**Comment by nicks** [comment]
i like this idea! Ya, so you could run the introductory examples against your own registry.

one thing I've seen people do is to have something like

```
registry = str(local('echo $REGISTRY')).strip() or 'grc.io/my-registry'
```

to simulate "config" variables in a Tiltfile. You'd also need some sort of way to substitute the registry in the yaml, e.g.,

```
k8s_yaml('myconfig.yaml')
substitute_regsitry('gcr.io/real-registry', gcr.io/my-registry')
```

is that what you had in mind?

**Comment by hausdorff** [comment]
Yeah, I think that's pretty much it. Ideally the YAML deployment layer would be pluggable, but I'm guessing that's way down your priority list.

**Comment by jazzdan** [comment]
I'm going to close this now that we have [`read_json`](https://docs.tilt.dev/api.html#api.read_json) and [`default_registry`](https://docs.tilt.dev/personal_registry.html). Let me know if that doesn't solve the problem for you @hausdorff!
