### ISSUE TITLE
Relationship between resource names and Docker images confused me

### ISSUE THREAD

**Issue by hausdorff** [windmilleng/tilt#1106]
Originally when I got started with the servantes demo, it took me about an hour before I realized that the image name in `fast_build` has to be the same as the name passed `k8s_resource`. See code snippet below. I'm still not sure why this is necessary (so you can link them together in the UI?), but either way, might be worth making this link more explicit somehow, perhaps by having one of them take the other as an argument.

```python
(fast_build('hausdorff/servantes-fe',
            'Dockerfile.go.base', '/go/bin/fe --owner ' + get_username())
  .add(repo.path('fe'), '/go/src/github.com/windmilleng/servantes/fe')
  .run('go install github.com/windmilleng/servantes/fe'))

k8s_resource('servantes-fe', port_forwards=port)
```

**Comment by nicks** [comment]
Ya, it's kind of magical right now. If they have the same name, it will auto-link them. If they don't, you have to do something like

```
image = (fast_build('hausdorff/servantes-fe',
            'Dockerfile.go.base', '/go/bin/fe --owner ' + get_username())
  .add(repo.path('fe'), '/go/src/github.com/windmilleng/servantes/fe')
  .run('go install github.com/windmilleng/servantes/fe'))

k8s_resource('mystuff', image=img, port_forwards=port)
```

to link them. I think there's a lot we could do to make this clearer, both in the documentation and in the error message...let me think on this a bit...

**Comment by nicks** [comment]
In the v0.8 release, we totally changed how k8s_resource objects are named.

Now, we pull out all k8s objects with containers, and give them an identifier of the form `(<name>(:<kind>(:<namespace>(:<group)?)?)?.`. We don't use the image name at all for naming.

more details on this in the end-user docs (https://docs.tilt.dev/api.html#api.k8s_resource) and the implementation spec (https://github.com/windmilleng/tilt.specs/blob/master/resource_assembly.md)

thanks for the feedback!
