### ISSUE TITLE
Adjust homebrew dependencies

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1155]
There are many ways that people can install `docker` or `kubectl`: be it docker for mac, gcloud, or something else. If you already have these things installed and you install Tilt with homebrew you get errors that suggest that the install failed, even if it succeeded:

```
The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/docker
Target /usr/local/bin/docker
already exists. You may want to remove it:
  rm '/usr/local/bin/docker'
```

```
The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/kubectl
Target /usr/local/bin/kubectl
already exists. You may want to remove it:
  rm '/usr/local/bin/kubectl'
```

Technically we don't depend on `kubectl` now with docker compose support anyways. Maybe we should just remove all dependencies and add a message advising users about what they should install?

Maybe there's a way to check if a dependency is fulfilled somehow in Homebrew?

**Comment by nicks** [comment]
ya, let's just remove the dependencies. if someone complains, we can talk about doing something more complex then.
