### ISSUE TITLE
Display in the Tiltfile log whether we think we are using a remote or local cluster

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1313]
Tilt's behavior changes depending on whether it thinks your kube context refers to a local cluster (docker ofr mac, minikube, microk8s) or a remote cluster. Right now you have to infer which Tilt thinks it is running in based off of if its trying to push an image to a remote registry, among other things.

I think we should log in to the Tiltfile log whether Tilt thinks the given kubecontext is local or remote.

Discussed [in the Tile channel](https://kubernetes.slack.com/archives/CESBL84MV/p1552568321082400) in Kubernetes slack

**Comment by nicks** [comment]
We currently block deploys to remote contexts unless you whitelist them
https://blog.tilt.dev/2019/09/09/august-tilt-commit-of-the-month.html

So I'm going to close this as obsolete
