### ISSUE TITLE
Function to set whether a kube context is local

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1314]
Right now we decide whether a cluster is local via [safe list of kube context names](https://github.com/windmilleng/tilt/blob/master/internal/k8s/env.go#L22). You could always rename one of these kube contexts to something else, so we should allow people to override this list from the Tiltfile.

Could be something as simple as:
```
assume_local_kube_context()
```

Or 
```
set_local_kube_context(context_name)
```

Or could our detection of local vs remote kubecontexts be more sophisticated?

Slightly related to #1096.

[Discussed in #Tilt channel](https://kubernetes.slack.com/archives/CESBL84MV/p1552568321082400) on Kubernetes slack.

**Comment by nicks** [comment]
I'm not sure that this is technically feasible?

Note that every local cluster has a unique way to load images into the cluster. There's not really a generic "local" cluster API, "local" just means "we've added a custom plugin to Tilt to load images into this type of cluster"
