### ISSUE TITLE
Docker for Mac Kubernetes DNS fails to resolve 

### ISSUE THREAD

**Issue by adamdecaf** [windmilleng/tilt#1319]
I'm trying to resolve a Kubernetes internal dns record like `fed.apps.svc.cluster.local`, but am having issues doing so. 

My setup is Docker for Mac (2.0.0.3), which ships with Docker 18.09.02 and Kubernetes v1.10.11.

The `Tiltfile` I'm using is pretty basic, each Kubernetes file has a Deployment, Ingress, etc copied from our production setup.

```
k8s_yaml("00-namespace.yml")

k8s_resource('proxy', './proxy/proxy.yml', port_forwards='9000:9000')
k8s_resource('ach', './ach/10-ach.yml', port_forwards='8080:8080')
k8s_resource('auth', './auth/11-auth.yml', port_forwards='8081:8080')
k8s_resource('ofac', './ofac/13-ofac.yml', port_forwards='8084:8080')
k8s_resource('paygate', './paygate/12-paygate.yml', port_forwards='8082:8080')
```

When I try and load `http://localhost:9000/v1/fed/ping` I get back a 502 error with the following from the `proxy` pod (running a Go HTTP reverse proxy).

```
2019/03/14 18:16:42.956286 reverseproxy.go:442: http: proxy error: dial tcp: lookup fed.apps.svc.cluster.local on 10.96.0.10:53: no such host
```

I've looked through the kubedns logs and everything looks okay. Is this a known issue?

**Comment by nicks** [comment]
Hmmm...I can't think of any Tilt-specific reason why this would fail to resolve.
 
Are you aware of `kubespy`? You could try running `kubespy trace svc apps/fed` and it will check for common misconfiguration issues.
https://blog.pulumi.com/kubespy-trace-a-real-time-view-into-the-heart-of-a-kubernetes-service

**Comment by adamdecaf** [comment]
Thanks. This was a couple bad configs on my part.
