### ISSUE TITLE
can't match containers if image in Tiltfile has tag

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1336]
See [@drubin's repro case](https://github.com/drubin/tilt-nodejs-example) -- in-place updates were failing for him with:

> In-place build needs container info.

On further investigation, this was b/c we aren't properly matching the container info [when processing a pod event](https://github.com/windmilleng/tilt/blob/dc0a49b5ad83ef7486d27fcbcd2e4a0ecc8fe1c2/internal/engine/upper.go#L683). in [`k8s.ContainerMatching`](https://github.com/windmilleng/tilt/blob/a28da6f326821f8b596df0d8b31775f9a74e4148/internal/k8s/container.go#L102), we compare the container's image ref with the image target's image ref. If the image target was initialized with a tag, then we're always checking if the running container's image matches `userimage:usertag`, which it NEVER will, because tilt-built images have the form `userimage:tilt-acb123`.

The short-term fix is to not match on tags in that particular part of the code -- it's not the most exact, but it'll only cause problems if someone's running multiple containers on the same pod with different tags. 😬 🤞

**Comment by drubin** [comment]
@maiamcc This solved it for me on a master branch so I think you can consider this fixed. 

Also, I think the approach is sane.

**Comment by maiamcc** [comment]
Amazing! Closing this issue.
