### ISSUE TITLE
Support (b)rowser from docker-compose

### ISSUE THREAD

**Issue by jlegrone** [windmilleng/tilt#1383]
Right now it seems like the only way to take advantage of tilt's "open in browser" feature is to have a `k8s_resource` with `port_forwards` [defined in your Tiltfile]( https://docs.tilt.dev/api.html#api.k8s_resource).

It would be awesome if [host-mapped service ports](https://docs.docker.com/compose/compose-file/#ports) were automatically discovered when running tilt against a docker-compose file. Supporting explicit configuration in Tiltfile would work too though!

**Comment by nicks** [comment]
Sorry about this! That's right, it doesn't work now w/ docker-compose. It's on our list of things to do! 

I think the main stumbling block is correctly parsing all the different ways to specify service ports 😬

**Comment by nicks** [comment]
The fix for this went out in today's release! 🎉
