### ISSUE TITLE
Tilt fails to apply namespace first

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#1515]
A user tried to load yaml containing both namespaces and objects declared in those namespaces.

Theoretically, tilt applies the namespaces first, so things work out.

For some reason, in this case, the objects declared in those namespaces are applied first, and yield an error because the namespaces have not yet been created. If you re-run tilt, the namespaces still exist, and things work fine.

Repro:
Save [this](https://gist.githubusercontent.com/fentas/bab98a9559368c4fef3b2fcb33a3356c/raw/f103d080cbe8445bf47cbc1a7d4f307f15c21c40/gistfile1.txt) into gist.yaml
make a Tiltfile that just has `k8s_yaml('gist.yaml')`
`tilt up`

expected:
the resources come up successfully
observed:
rook-ceph-operator fails to apply with:
```
       ERROR: kubectl apply:
       stderr: Error from server (NotFound): error when creating "STDIN":
       namespaces "rook-ceph-system" not found
```
(note, if reproing multiple times, you'll need to `tilt down` between attempts, to ensure the namespace gets deleted)

The same problem probably applies to CRDs.

**Comment by landism** [comment]
When applying global yaml, tilt [does sort by namespace](https://github.com/windmilleng/tilt/blob/7b4946d40944c1d10368499a03345d67cf21d0db/internal/engine/global_yaml_buildcontroller.go#L99). I think the issue here is that rook-ceph-operator is in a normal resource, not global yaml, and global yaml application happens in parallel with resource builds, so there's a race.

(also, tilt makes no attempt to apply CRDs first, and it should)

**Comment by maiamcc** [comment]
@landism 

a. do you have a sense of how much work this'd be to fix?
b. does it seem that just removing the concept of global yaml (which we've been meaning to do for a while anyway) would address this issue?

**Comment by landism** [comment]
> do you have a sense of how much work this'd be to fix?

Nope! I'd lean towards applying global yaml synchronously and always making it higher priority than other resources, but I haven't really looked into what's involved in that (global yaml is currently handled via a separate controller, so there miiight be some complication to synchronize them?)

> does it seem that just removing the concept of global yaml (which we've been meaning to do for a while anyway) would address this issue?

I've heard mention of this but I'm not entirely sure what it means in practice. We've got k8s objects (e.g., namespaces) that aren't really associated with tilt resources, and we need to apply them to the cluster at some point. Whether that's as part of a tilt resource or not, we still need code to take those non-tilt-resource objects (which one might refer to as "global yaml" or something else) and apply them to k8s at some point, and that seems unrelated to the tilt-resourciness of it.
