### ISSUE TITLE
Cannot see docker build errors

### ISSUE THREAD

**Issue by grampelberg** [windmilleng/tilt#1516]
When there is an error with the docker build, I don't get much useful output.

```bash
CMD /foobar
 │ Tarring context…
   ╎ Created tarball (size: 43 kB)
 │ Building image
   ╎ ERROR IN: [builder 7/7] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/foobar/...
ERROR: ImageBuild: executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/foobar/...]: exit code: 2
```

## Environment

- Docker for Mac 2.0.3.0 (engine 18.09.3)
- Tilt v0.7.13

**Comment by nicks** [comment]
@dbentley @landism is this bug fixed by https://github.com/windmilleng/tilt/pull/1523 ?

**Comment by nicks** [comment]
i haven't heard anything on this, and presume it's fixed, so marking closed

**Comment by grampelberg** [comment]
@nicks yup, working for me!
