### ISSUE TITLE
Dev versions of Tilt built with modules can't be run outside of `$GOPATH`

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1520]
As reported by @dbentley and in #tilt: Tilt expects to be able to find the HTML/CSS/JS for the web UI when built off of master. It uses `$GOPATH` to do that. If you try to run Tilt outside of `$GOPATH` it fails with:

```
Error: Could not locate Tilt source code: cannot find package "github.com/windmilleng/tilt/internal/hud/server"
```

I _think_ we should bake in the directory of the git checkout at build time to make this less brittle, but I'm not sure.

**Comment by landism** [comment]
FWICT, everyone who has seen this issue was building Tilt using modules, which is currently rather out of the supported dev flow. We'll need to tackle this when we switch the build to use modules.

**Comment by jshaughn** [comment]
note: tilt now requires go 1.12 to build, not 1.11 as stated on the website.

**Comment by nicks** [comment]
@jshaughn thanks! updating now
