### ISSUE TITLE
Live update only seems to work for first container in pod

### ISSUE THREAD

**Issue by mseashor** [windmilleng/tilt#1522]
First off - I'm really liking Tilt so far - fast in place builds with live_updates are great!   It just seems I've hit an issue with live_updates for a container which isn't the first container in a pod.  

**Scenario**: Two pods in a container need to support live updates.  FYI: In reality, if two containers with live updates aren't supported, we could probably get away with one container supporting live updates but an error indicating **only** the first container in a pod is supported  would be incredibly helpful (it took me forever to figure out that's why it seems live updates weren't working).

**Test Case**: I've attached the simplest possible test case I can come up with - basically just two apache servers (apache1 and apache2) servers running on different containers/ports in the same pod with live updates to their index.html.  It is a bit contrived, but illustrates the point.

- docker + kubernetes yaml + Tiltfile to reproduce: [only_first_container_live_reloads.zip](https://github.com/windmilleng/tilt/files/3105818/only_first_container_live_reloads.zip).

- Tiltfile for reference (also in zip)
```
k8s_resource_assembly_version(2)
  
docker_build('test.com/apache1','apache1',
  live_update=[
    sync('apache1/public_html', '/usr/local/apache2/htdocs'),
  ]
)
docker_build('test.com/apache2','apache2',
  live_update=[
    sync('apache2/public_html', '/usr/local/apache2/htdocs'),
  ]
)

k8s_yaml('k8s.yaml')

k8s_resource('example-deployment', port_forwards=["8080:80","8081:81"])
```
- Commands to reproduce:
```
unzip only_first_container_live_reloads.zip
cd tilt_issue_only_first_container_live_reloads
tilt up                
#(switch to a new terminal)

echo "apache11" > apache1/public_html/index.html   

#Note that live reload works on apache1 (first container in pod)
# Ex: 
# ──┤ Rebuilding: example-deployment #├──────────────────────────────────────────# ──
#  → Updating container…
# Copying 1 file(s) to container: 0551cadab8

echo "apache22" > apache2/public_html/index.html  

#Note live reload does not work on apache2 and it is fully rebuilt - sometimes getting into a crash loop
```
- The message in tilt when failing to live update is: ```falling back to next update method because: don't have info for deployed container (often a result of the deployment not yet being ready)``` (https://github.com/windmilleng/tilt/blob/master/internal/engine/extractors.go#L90)
 
- This issue seemed similar to: https://github.com/windmilleng/tilt/issues/1336, so I purposely don't set tags on the images.

- tilt doctor information (Docker for Mac - Stable + tilt 0.8.0 installed with brew)
```
Tilt: v0.8.0, built 2019-04-22
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.39
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-for-desktop
- Cluster Name: docker-for-desktop-cluster
- Namespace: default
- Container Runtime: docker
- Version: v1.10.11
---
Thanks for seeing the Tilt Doctor!
Please send this info along when filing bug reports. 💗
```

- Thanks for any help and let me know if you need additional information, etc.

**Comment by maiamcc** [comment]
Hi @mseashor! You're correct, we currently only support LiveUpdates for the first container in a pod. (You're also correct that we should have better messaging around that 😳 ) Thank you for SUCH a detailed bug report, and I'm sorry our messaging didn't make this clear from the get-go. I'll go add some messaging around that now, and we'll be sure to ping you when we implement multi-container support!

**Comment by mseashor** [comment]
Sounds great.  Thanks!

**Comment by maiamcc** [comment]
Alright @mseashor, updated the error messaging -- you should get a warning when we parse a tiltfile and find LiveUpdates for anything but the first container of the pod. (This code is on `master` if you're building from source, otherwise look for it soon in a release near you!)

I'm going to leave this issue open and relabel it from bug --> enhancement, **for anyone else who wants LiveUpdate support for multiple containers to chime in.**

**Comment by maiamcc** [comment]
Hey @mseashor, I don't know if you're still Tilt-ing, but if you are--we've implemented this! 🎉 

We're currently soft-launching this functionality: you can put the line `enable_feature('multiple_containers_per_pod')` in your Tiltfile to enable it, and add `live_update`'s to your heart's content. Let me know if you take this feature for a spin, and how it works for you!

**Comment by kvokka** [comment]
Thank you @maiamcc for the great feature!

Please, keep in mind that `enable_feature('multiple_containers_per_pod')` is undocumented.

At least the link to this issue may helps. Because now for getting the new features the developer should search with `enable_feature`. It is not very obvious.

**Comment by nicks** [comment]
@kvokka the feature is on by default now. you shouldn't need to enable it explicitly anymore.

**Comment by kvokka** [comment]
Thank you for such a quick response.

Cool! Will update `Tiltfile`. But do you have any special place with features incubator (like this one?).
