### ISSUE TITLE
should surface events from `kubectl describe`

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#1584]
`kubectl describe` and `kubectl get events` often have important info when a resource is failing to deploy for some reason (e.g., out of cpu, missing volume, missing secret, etc)

Tilt should surface this info in some way.

Recently, this has been getting raised at least once a week by somebody (either in-person user or in the #tilt k8s slack channel)

**Comment by fentas** [comment]
Right now, if a resource is misconfigured e.g. missing configmap etc. tilt will only show pending.

**Comment by nicks** [comment]
This has been available for a while. Tilt should surface events associated with the resources you deploy
