### ISSUE TITLE
live_update: sync()'s local_path needs to match docker_build()'s context for it to be useful

### ISSUE THREAD

**Issue by fkaleo** [windmilleng/tilt#1606]
If the user uses live_update and set sync()'s local_path to only a subset of the files being set to watch by docker_build() (docker_build()'s context seems to be used to determine which files are being watched), then full builds will be re-triggered for any change in the files not included in sync().

This behaviour is counter-intuitive especially due to the presence of fall_back_on(). I expect that no full rebuild will be triggered unless a path is specified in fall_back_on().

Another way to look at it is through the following use case:
At the moment, if the user wants to only trigger a fast-sync on a single file and not having any full rebuild triggered in case any other file changes, it seems necessary to add a sync() encompassing all possible files that might change.

**Comment by maiamcc** [comment]
Thanks for the issue @fkaleo !

Oof yeah, I see how that could be annoying. You're not the first person to bring this up, and we're trying to figure out the right way to go about it. To give some context, the case we want to AVOID is where you've changed a file that actually belongs in your Docker image but that you didn't include in a sync, and now the code running in your container doesn't accurately reflect what's on your local.

A question about your use case: are the files triggering the full build files that you actually want in your Docker image, or just incidental?

**Comment by fkaleo** [comment]
Yeah, it's important that local state is always reflected in the pod.

The files that are triggering the rebuild are part of the Docker image but for fairly bad reasons (imho) they are not generated during the docker image build process but before.

**Comment by maiamcc** [comment]
Hmm then I'm not sure I quite understand: file X _is_ part of your docker image, but you don't want any subsequent changes to that file to end up in your container (either via live update or via docker build)? Can you explain a bit more?

Regardless, I believe you can put that file in a `.tiltignore` to stop it from triggering tilt builds!

**Comment by fkaleo** [comment]
Oh no I want file X to end up in the container but via a sync not via an image build.

**Comment by fkaleo** [comment]
Sorry I'm not explaining myself very well.

**Comment by maiamcc** [comment]
Ah! Then why wouldn't you just add it as a sync? I'm confused. Or is your complaint that the way Tilt handles it when you forget is to do a whole image build?

For what it's worth, a very common pattern we see is for someone to just sync their whole docker context directory:
```
docker_build('my_img', '/src', live_update=[ sync('/src', '/') ]
```

**Comment by fkaleo** [comment]
My Dockerfile adds files individually, not an entire folder.
It contains something like:
COPY build/mybinary /usr/bin/mybinary

And the Tiltfile:
docker_build('myimage', '.', dockerfile='Dockerfile',
  live_update=[
    sync('build/tsdb-gw', '/usr/bin/tsdb-gw'),
    restart_container(),
)

**Comment by fkaleo** [comment]
Yeah so I ended up doing a bit of a trick like you suggested:
```
docker_build('myimage', '.', dockerfile='Dockerfile',
  live_update=[
    sync('build/mybinary', '/usr/bin/mybinary'),
    sync('.', '/tmp/src'), # workaround
    restart_container(),
)
```

**Comment by fkaleo** [comment]
I guess the point is that when the Dockerfile adds files individually, it kind of breaks down.

**Comment by fkaleo** [comment]
Ah yes! I forgot my context when I wrote the bug report:
Some other files are going to be changing that don't end up in the container and I don't want those files to trigger rebuilds.

**Comment by fkaleo** [comment]
I am starting to think I went about it the wrong way and specified the wrong docker context.

**Comment by maiamcc** [comment]
Oh! Then yes, I think what you want is `.tiltigore`: https://docs.tilt.dev/other_tilt_features.html

Basically, you can keep files from triggering Tilt builds, bu they're still eligible to end up in your docker image.

`.tiltignore` uses `.dockerignore` syntax, so you can ignore specific files or file extensions, OR use it as a whitelist by ignoring * and then un-ignoring only the files you want to trigger stuff (here's an [example of this pattern with .gitignore](https://jasonstitt.com/gitignore-whitelisting-patterns), which is slightly different syntax but the same idea). Is that helpful?

**Comment by fkaleo** [comment]
Here is the deal:
Dockerfile needs to run from the top directory atm as it copies files from various subdirectories of the top one:
```
COPY scripts/...
COPY build/...
```
Hence the docker context set here to `'.'`:
`docker_build('myimage', '.', dockerfile='Dockerfile', ...)`

However there are other subdirectories containing files that have nothing to do with the Dockerfile essentially nor the build. Those files changing should not trigger anything. I guess using .tiltignore as you suggest will do the trick. However it feels like there was a more intuitive way.

**Comment by fkaleo** [comment]
In fact, I'm curious as to why all files in the docker context are being watched for changes. It feels like only source files in the ADD/COPY directives should be watched no?

**Comment by maiamcc** [comment]
Yeahhhh that's definitely on our to-do list. For what it's worth, we _have_ been thinking about ways to do this better (i.e. only watching/rebuilding on reasonable file changes) -- if you're curious, you can [read our spec](https://github.com/windmilleng/tilt.specs/blob/master/slim_build_context.md). In the meantime though, try `.tiltignore` and let me know if it works for you?

**Comment by fkaleo** [comment]
Great to know!
I added that in my `.tiltignore`:
```
*
!build/mybinary
```

and it seems to work :)

**Comment by fkaleo** [comment]
Essentially I am manually whitelisting what is in my sync() and ADD/COPY directives. In the end I have the same list of files written 3 times.

**Comment by fkaleo** [comment]
Indeed, in the spec you linked there is the right thing (tm) :)

>     Watch only an image's actual dependencies instead of its full build context.
> 
>     e.g., parse each Dockerfile, find ADDs and COPYs, and only watch the files that get added and copied.

**Comment by maiamcc** [comment]
Sigh. Yeah, that's really not ideal. I'll add a +1 next to that feature for you.

But glad it works! I'm going to close this issue since you got it working, but feel free to reach out if you need anything else -- and we'll let you know when we ship that feature!

**Comment by fkaleo** [comment]
Thanks for your great help!
