### ISSUE TITLE
helm(): perhaps prevent resources under templates/tests/ to be activated

### ISSUE THREAD

**Issue by fkaleo** [windmilleng/tilt#1614]
If a helm chart contains test resources under templates/tests/ they probably should not be deployed by `tilt up`

**Comment by nicks** [comment]
Good call!

**Comment by jazzdan** [comment]
This should be fixed in https://github.com/windmilleng/tilt/commit/6269fcd766700851214b8ab099bd769ea45c4eae

Thanks for the suggestion @fkaleo!

**Comment by fkaleo** [comment]
You guys are quick :) Thanks!
