### ISSUE TITLE
Docs for Tiltfile helpful workarounds/functions

### ISSUE THREAD

**Issue by dbentley** [windmilleng/tilt#1616]
We should describe useful tips and tricks, like how to use `str` on the blob created by `local` and how to die on the wrong cluster.

[as mentioned in Kubernetes slack]

**Comment by jazzdan** [comment]
Should this live on https://github.com/windmilleng/tilt.build ?

**Comment by jazzdan** [comment]
Moved to https://github.com/windmilleng/tilt.build/issues/179
