### ISSUE TITLE
k8s_yaml doesn't work where `kubectl apply -f` does

### ISSUE THREAD

**Issue by ndarilek** [windmilleng/tilt#1650]
Trying to use Tilt to do the following:

1. Deploy Helm into a new cluster, Minikube in this instance.
2. Deploy KubeDB and its catalog.
3. Deploy a Postgres database.

I have the following Tiltfile:

```
local("helm init --wait")
local("helm upgrade --install kubedb-operator appscode/kubedb --version 0.12.0  --namespace kube-system")
local("helm upgrade --install kubedb-catalog appscode/kubedb-catalog --version 0.12.0 --namespace kube-system")
k8s_yaml("postgres.yaml")
```

And the following postgres.yaml:

```
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
spec:
  version: "11.2"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  terminationPolicy: DoNotTerminate
```

Note that you have to run `tilt up` a couple times, because the first Helm installation needs to install CRDs and `--wait` hangs indefinitely.

After a few `tilt up`s, I get this error:

```
      K8s objects not included in the resources above:                                                                                                                                   
      k8sPostgres-postgres                                                                                                                                                               
    ERROR:                                                                                                                                                                               
       Error: Error upserting k8s_yaml: kubectl apply:                                                                                                                                   
       stderr: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "postgres.mutators.kubedb.com": the server is currently   
       unable to handle the request                                                                                                                                                      
       : exit status 1                                                                                                                                                                   
```

However:

```bash
$ kubectl apply -f postgres.yaml 
postgres.kubedb.com/postgres created
```

I'm not clear on why this fails in Tilt, and there don't seem to be any additional knobs in `k8s_yaml` to tweak.

Thanks.

**Comment by dbentley** [comment]
Interesting bug; thanks for reporting it.

Tilt injects labels before applying yaml so we can connect k8s resources back to Tilt reosurces. I wonder if the labels we're adding make the handler upset?

Do you use kubedb a lot? Are you an expert/implementer in it, or more of a user? (This is my first time hearing of it, so this is a pure guess)

**Comment by ndarilek** [comment]
Just a user.


Is it possible to get logs of what commands are being executed? `tilt up 
-v` doesn't seem to do it.


Thanks.

**Comment by nicks** [comment]
`--klog 8` should give you all the k8s api calls

**Comment by ndarilek** [comment]
So `tilt up --klog 8`?


Not seeing any commands for the `k8s_yaml` step.


Thanks.

**Comment by landism** [comment]
> Not seeing any commands for the `k8s_yaml` step.

Sorry about that! `--klog 8` is for k8s api calls, but tilt execs `kubectl apply` rather than using the k8s api to apply yaml. I've fixed this in #1674 and will post back here shortly when we have a release available with this change.

**Comment by landism** [comment]
Tilt 0.8.7 has been released, and if you run with `--klog 1` or higher, you'll see kubectl's input and output (and its internal api calls as well if you go high enough)

**Comment by ndarilek** [comment]
Where should I see these? `tilt up --klog 8` gives me the exact same errors.

**Comment by nicks** [comment]
Digging into this now. I was able to reproduce this error. A couple observations (more for us / the Tilt team than for you):

This document was helpful for info on how to install kubedb:
https://kubedb.com/docs/0.9.0/setup/install/

Note the instructions "Step 2: wait until crds are registered". It would be nice if a Tiltfile had a better way to do this kind of thing. Their instructions for it aren't great and require a human at the keyboard.

When I tried to run `kubectl apply -f postgres.yaml`, I get the error:

```
$ kubectl apply -f postgres.yaml 
Error from server (Forbidden): error when creating "postgres.yaml": admission webhook "postgres.validators.kubedb.com" denied the request: spec.storage.storageClassName "standard" not found
```

When I run `tilt up`, I get:

```
ERROR: kubectl apply:
stderr: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "postgres.mutators.kubedb.com": the server is currently unable to handle the request
: exit status 1
```

When I run `tilt up --klog 8`, I get

```
I0619 13:18:45.740351    9924 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"postgreses.kubedb.com \"postgres\" not found","reason":"NotFound","details":{"name":"postgres","group":"kubedb.com","kind":"postgreses"},"code":404}
I0619 13:18:45.740748    9924 request.go:942] Request Body: {"apiVersion":"kubedb.com/v1alpha1","kind":"Postgres","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kubedb.com/v1alpha1\",\"kind\":\"Postgres\",\"metadata\":{\"annotations\":{},\"name\":\"postgres\",\"namespace\":\"default\"},\"spec\":{\"storage\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"storageClassName\":\"standard\"},\"storageType\":\"Durable\",\"terminationPolicy\":\"DoNotTerminate\",\"version\":\"11.2\"}}\n"},"name":"postgres","namespace":"default"},"spec":{"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"standard"},"storageType":"Durable","terminationPolicy":"DoNotTerminate","version":"11.2"}}
I0619 13:18:45.740786    9924 round_trippers.go:416] POST http://127.0.0.1:8080/apis/kubedb.com/v1alpha1/namespaces/default/postgreses
I0619 13:18:45.740793    9924 round_trippers.go:423] Request Headers:
I0619 13:18:45.740798    9924 round_trippers.go:426]     Accept: application/json
I0619 13:18:45.740803    9924 round_trippers.go:426]     Content-Type: application/json
I0619 13:18:45.740807    9924 round_trippers.go:426]     User-Agent: kubectl/v1.14.2 (linux/amd64) kubernetes/66049e3
I0619 13:18:45.746334    9924 round_trippers.go:441] Response Status: 500 Internal Server Error in 5 milliseconds
I0619 13:18:45.746352    9924 round_trippers.go:444] Response Headers:
I0619 13:18:45.746359    9924 round_trippers.go:447]     Content-Type: application/json
I0619 13:18:45.746365    9924 round_trippers.go:447]     Date: Wed, 19 Jun 2019 17:18:45 GMT
I0619 13:18:45.746370    9924 round_trippers.go:447]     Content-Length: 399
I0619 13:18:45.746434    9924 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"postgres.mutators.kubedb.com\": the server is currently unable to handle the request","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"postgres.mutators.kubedb.com\": the server is currently unable to handle the request"}]},"code":500}
I0619 13:18:45.746737    9924 helpers.go:196] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"STDIN\": Internal error occurred: failed calling webhook \"postgres.mutators.kubedb.com\": the server is currently unable to handle the request",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "failed calling webhook \"postgres.mutators.kubedb.com\": the server is currently unable to handle the request"
      }
    ]
  },
  "code": 500
}]
```

**Comment by ndarilek** [comment]
Oh, you know, I may not have scrolled the logs up to get those earlier 
messages. Apologies for not being more thorough.


I don't know if there is a meaningful way to wait for the CRDs to be 
available--I didn't immediately find one with kubectl--but my plan was 
to basically let the first `tilt up` fail, then run it again, assuming 
the CRDs were installed. But when I attempted this last time, the 
`kubectl apply -f ...` worked even though the `tilt up` didn't. Not sure 
if running the installation command for the CRDs caused them to become 
temporarily unavailable somehow--maybe the controller restarts and fails 
the subsequent attempt to immediately install Postgres?

**Comment by nicks** [comment]
OK, playing around with this, I don't think this is a Tilt bug.

Basically, what's happening is that when you run the `helm install`, Kubernetes restarts all the operators for your CRDs (i.e., the job that knows how to interpret a Postgres resource)

When you restart them, it takes about a minute for the operators to be able to handle requests. While they're initializing, any operations on Postgres resources will fail with "the server is currently unable to handle the request"

Here's an updated Tiltfile that I hope will work a lot better. Note the `sleep` call to wait for everything to come up.

```
operator = str(local("kubectl get deployments kubedb-operator -n kube-system --ignore-not-found"))
if not operator:
  local("helm init --wait")
  local("helm upgrade --install kubedb-operator appscode/kubedb --version 0.12.0  --namespace kube-system")
  local("helm upgrade --install kubedb-catalog appscode/kubedb-catalog --version 0.12.0 --namespace kube-system")
  local("sleep 60")

k8s_yaml("postgres.yaml")
```

Though honestly, the recommended option for using Tilt with Helm is to use `helm fetch` and `helm template`, as described here:
https://docs.tilt.dev/helm.html

That way, Helm is only responsible for generating the yaml for kubedb. Then Tilt manages the install of kubedb to the cluster. This can be a bit simpler than having both Tilt and Helm talking to Kubernetes and stepping on each other's toes.

**Comment by nicks** [comment]
(I closed the issue, but happy to re-open if you don't think this addresses the problem, or if you want to jam a bit more on what a `helm fetch` / `helm template` solution might look like)

**Comment by ndarilek** [comment]
This is probably fine. Thanks for showing me the Tilt way to do this.
