### ISSUE TITLE
update nudge broken

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#1658]
currently the update check is broken

![Screen Shot 2019-05-20 at 11 38 24 AM](https://user-images.githubusercontent.com/278641/58012022-cdce4600-7af3-11e9-83b3-a9fd376ca127.png)

this error message shows up in the logs:

> error checking github for latest Tilt release: error getting release for windmilleng/tilt: GET https://api.github.com/repos/windmilleng/tilt/releases/latest: 403 API rate limit exceeded for 95.215.121.72. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 40m51s]

**Comment by nicks** [comment]
It might make sense to use our gcp bucket instead of github for version checks

**Comment by jazzdan** [comment]
this has been fixed.
