### ISSUE TITLE
Feature request: can override Dockerfile entrypoint

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1680]
In FastBuild, you could specify an entrypoint that would override the existing Dockerfile's entrypoint. (This was useful if e.g., you wanted to use the same Dockerfile for dev and prod, but wanted slightly different behavior in dev; just override the entrypoint.)

This functionality is not available with `docker_build` + `live_update`, and probably should be.

I propose additional syntax for `docker_build`:

```
docker_build('my_img_name', './context', entrypoint='dev_thing.sh', live_update=[...])
```
(This functionality could be used with or without `live_update`.)

NB: this request came in via Mindspace: 
> We use the same Dockerfile for dev + production, and the docker "defaults" are typically production so anything dev related is an override.

**Comment by nicks** [comment]
fwiw, this is specifically for the case where you want to use `node` to run your prod build but `nodemon` to run your live_update build. If we add this, we should make sure we add it to the nodejs documentation.

**Comment by dexhorthy** [comment]
+1 on this -- FWIW I ended up moving the custom entrypoint(s) into a Kustomize overlay for my dev env, but it would be great to be able to control this from the Tiltfile as well.

**Comment by maiamcc** [comment]
👋 hey folks! this is implemented in #1833 and #1831, and is live in [v0.9.3](https://github.com/windmilleng/tilt/releases/tag/v0.9.3) 🎉 take it for a spin and let me know if it meets your needs!

[documentation here](https://docs.tilt.dev/api.html#api.docker_build), but briefly, the syntax is:
```
docker_build('my_image_name', './context', entrypoint='./dev_entrypoint.sh')
```
(Also works with `custom_build`)

**Comment by maiamcc** [comment]
hey @dexhorthy, did you get a chance to try this out?

**Comment by dexhorthy** [comment]
@maiamcc I have not unfortunately, thanks for the ping though, missed this initially. Will check it out when I have a sec

**Comment by maiamcc** [comment]
I'm gonna go ahead and close this issue, but @dexhorthy lmk when you get a chance to try it/if you run into any problems!
