### ISSUE TITLE
Order of k8s_yaml commands

### ISSUE THREAD

**Issue by AleF83** [windmilleng/tilt#1737]
My `Tiltfile` is as following:
```python
k8s_yaml('path/to/yaml/that/creates/namespace')

k8s_yaml('path/to/deployment/that/created/in/namespace/above')
```

When I'm running `tilt up` I got the namespace created but error on creating deployment that the namespace doesn't exist.

The second time it runs ok.

**Comment by jazzdan** [comment]
Interesting! I would imagine this would be taken care of by [this change](https://github.com/windmilleng/tilt/commit/7b4946d40944c1d10368499a03345d67cf21d0db). Thoughts @landism?

**Comment by landism** [comment]
#1515

**Comment by davae1an** [comment]
Having the same problem 

`
# Kafka Setup

k8s_yaml([
    'deploy/kafka/00-namespace/00-namespace.yml',
    'deploy/kafka/01-zookeeper/01-zookeeper-service.yml',
    'deploy/kafka/01-zookeeper/02-zookeeper-deployment.yml',
    'deploy/kafka/02-kafka/kafka-broker1-deployment.yml',
    'deploy/kafka/03-yahoo-kafka-manager/kafka-manager-deployment.yml',
    'deploy/kafka/03-yahoo-kafka-manager/kafka-manager-service.yml',
])


`
