### ISSUE TITLE
Implement load() in Tiltfile (i.e. import other Tiltfiles)

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#1748]
One way that people want to organize their code is to have 
1) A Tiltfile per service
2) A Tiltfile that brings services together by loading the per-service Tiltfile

A good first step would be to implement the starlark load() function, just to let people organize their Tiltfiles. Then watch if any common patterns emerge.

**Comment by drubin** [comment]
I think it would also be good to have tilt scan for `Tiltfile`'s in subdirectories and then automatically load those.

**Comment by nicks** [comment]
This is currently implemented!
https://docs.tilt.dev/api.html#api.include
to load other tiltfiles just for their resources
and
https://docs.tilt.dev/api.html#api.load
to load variables from other tiltfiles
