### ISSUE TITLE
Trouble migrating from fast_build to live_update

### ISSUE THREAD

**Issue by dexhorthy** [windmilleng/tilt#1762]
```shell
$ tilt version
v0.9.0, built 2019-06-19
```

Hi folks -- looking to get a few things moved over to live_update. I'm not sure I'm doing things quite right, but I'm seeing some noticeable performance differences in the LiveUpdate version, and was wondering if there were any tweaks I can make to get closer to what we had with FastBuild.

I have a [mono-ish repo](https://github.com/replicatedhq/enterprise-gtm-starter) with 5 dev services:

1. React frontend (webpack dev server)
1. NodeJS backend
1. unit test pod
1. tslint pod
1. integration test pod that runs black-box http tests against running NodeJS backend

with fast_build, I can do things like:

-  change source code for frontend, tilt copies in new sources, WDS hot reloads (~2s feedback loop)
- change source code for backend, tilt copies in new sources and restarts container (~10s feedback loop)
- when backend sources are changed, sources copied in and lint/unittest/integrationtest containers are also restarted (~5-10s feedback loop for unittests/linting, slightly longer for black-box integration tests)
- when integration tests are added, integrationtest container re-runs with the updated sources

With live_update, the migration I've done seems to not be as good at detecting which containers need to be restarted at which times. For example, I'll edit some frontend code, and **4-5 services will restart**, which makes the feedback loop a lot slower for any service. I'm wondering if maybe its because in live-update land I use one shared Dockerfile for each of these services that does an `ADD . /app`? Do i need to split up into different Dockerfiles that each add the paths they need? I'm even seeing `frontend` getting kicked to ContainerCreating with `live_update`, even though I don't have a `restart_container()` in my `live_update`.

### Fast Build config

```python
# Tiltfile
# vi: set ft=python

overlay = local('if [ -d kustomize/overlays/dev_$USER ]; then printf "dev_$USER"; else printf "dev"; fi')
k8s_yaml(kustomize("./kustomize/overlays/%s" % overlay))

repo = local_git_repo(".")

def nodejs_build(image_name, entrypoint, paths):
    img = fast_build(image_name, 'Dockerfile.tilt', entrypoint)

    for path in ['package.json', 'package-lock.json', 'tslint.json', 'tsconfig.json']:
        img.add(repo.path(path), '/app/%s' % path)

    for path in paths:
        img.add(repo.path(path), '/app/%s' % path)

    img.run('npm install', trigger=['package.json', 'package-lock.json'])
    return img

nodejs_build('backend', 'npm run --silent start-be', ['src/server'])
nodejs_build('frontend', 'npm run --silent start-fe', ['src/index.js', 'src/client', 'public']).hot_reload()
nodejs_build('unittests', 'npm run --silent test:watch', ['src/server', 'test']).hot_reload()
nodejs_build('lint', 'npm run --silent tslint:watch', ['src/']).hot_reload()
nodejs_build('integrationtest', 'npm run --silent integration-test-be', ['src/integrationtest', 'src/server', 'test'])
```

Dockerfile

```dockerfile
FROM node:8
RUN mkdir /app
WORKDIR /app
```
### Live Update

Tiltfile.liveupdate

```python
# vi: set ft=python

overlay = local('if [ -d kustomize/overlays/dev_$USER ]; then printf "dev_$USER"; else printf "dev"; fi')
k8s_yaml(kustomize("./kustomize/overlays/%s" % overlay))

repo = local_git_repo(".")

def sync_build(name, paths=[], restart=False):
    update = [ sync(dir, "/app/%s" % dir) for dir in paths ]
    if restart:
        update.append(restart_container())

    docker_build(
        name,
        ".",
        dockerfile="Dockerfile.liveupdate",
        live_update=update
    )


sync_build("backend", [ "src/server" ], restart=True)
sync_build("frontend", [ "src/index.js", "src/client", "public" ])
sync_build("unittests", [ "src/server", "test" ])
sync_build("lint", [ "src" ])
sync_build("integrationtest", [ "src/integrationtest", "src/server", "test" ])

```

Dockerfile.liveupdate

```
FROM node:8-alpine
RUN mkdir /app
WORKDIR /app
ADD package.json /app/package.json
ADD package-lock.json /app/package-lock.json
RUN npm install

ADD . /app
```

**Comment by landism** [comment]
> I'm wondering if maybe its because in live-update land I use one shared Dockerfile for each of these services that does an ADD . /app? 

Close! It's because for each of the services, the config defines a `docker_build` with build context (second arg) `"."`. This means Tilt will consider all files under `"."` a dependency of that service, and any changes will cause a rebuild + restart. `live_update` will override that behavior only for any paths given to `sync`, and give you the behavior you want. This means that if you change a file in `public`, you'll get a live update on `frontend`, and a full rebuild on all other services, since they don't have a `sync` for `public`.

We've recently added an [`only` parameter to `docker_build`](https://docs.tilt.dev/api.html#api.docker_build) for this. It's possible all you need to do is add `only=paths` to your `docker_build` (or `only=paths + ['package.json', 'package-lock.json', 'tslint.json', 'tsconfig.json']`? I'm not sure if you're worrying about `npm install` with live_update, but then you probably also want to put a `run` for that in your `live_update`)

**Comment by dexhorthy** [comment]
@landism aha, that makes sense. `only` worked like a charm -- thanks! Feel free to close.
