### ISSUE TITLE
Building image takes 30 seconds on each source file modification

### ISSUE THREAD

**Issue by develar** [windmilleng/tilt#1777]
And I have no idea how to ask tilt to show me full build log instead of just "Building Image".

Moreover, I think that tilt by default should show full build log if it takes more than, say, 30 seconds (to blame developer who wrote bad Dockerfile).

1. `cmd + c` and `tilt up` again build image in 1-2 seconds (as expected).
2. works instantly without tilt — docker build or docker compose (but I completely removed compose in favour of tilt/k8s).

```
Tilt: v0.9.0, built 2019-06-19
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.39
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop
- Context: docker-for-desktop
- Cluster Name: docker-for-desktop-cluster
- Namespace: default
- Container Runtime: docker
- Version: v1.10.11
---
```

The same behaviour for edge docker for mac.

**Comment by develar** [comment]
Dockerfile — https://github.com/electron-userland/electron-build-service/blob/16a4012fe883c0a2c81940c32ca736e419502b3f/cmd/builder/Dockerfile#L1 (I am sure that problem in `go mod download`, but without logs I can only guess).

**Comment by nicks** [comment]
Huh, what a weird bug! Usually Tilt shows build logs by default. I'm not sure why it would just hang on "Building image..." for 30sec. Trying to repro now

**Comment by develar** [comment]
I searched across docs, and tried `--debug` and `--verbose`, and still, cannot figured out how to force tilt to show me full build log.

Tilt is so awesome (at first day of usage I found critical bug because of clear log view on shutdown), thanks a lot for a great product.

**Comment by nicks** [comment]
I can repro. There's a bug in how we're interpreting the results of the docker build api. fix on the way!

I'm still digging into why the build times are taking so long...that's a separate thing

Just to make sure I'm testing the right thing: when it takes 30 seconds to rebuild, which files are you changing? The go source files?

**Comment by develar** [comment]
> Just to make sure I'm testing the right thing: when it takes 30 seconds to rebuild, which files are you changing? The go source files?

Yes, go source file. e.g. `gopool.go` In the tilt logs I see something like "File foo is changed" (so, it means that tilt correctly detects changed files and not the whole project file set).

**Comment by nicks** [comment]
OK, the fix for the output is in review! Now let's talk about why the build is taking so long.

The call that's taking most of the time is the `RUN go build`. 

Every time you make a file change, you have to recompile all the Go code from scratch. The dockerfile doesn't let you keep the Go compiler cache between builds.

The usual fix we recommend is to use live_update to recompile the Go code inside the container, as described here: https://docs.tilt.dev/live_update_tutorial.html. That way, it re-uses the Go compiler cache. But that means you'd have to use a single-stage build that puts all the Go source code and Go tools in the main container. Does that make sense?

**Comment by nicks** [comment]
OK, the fixes to buildkit output should be in the latest release, and the `go build` slowness can be fixed with live_update. I'm going to close this issue, but happy to re-open if you need additional help with this!
