### ISSUE TITLE
File watch leak

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1817]
We've had at least one report of the number of watches reported by the expvars server increasing steadily after each save. From @dotellie in the #tilt channel:

> Hm so I have that page open right now while doing some development. Refreshing it periodically, I can see that the number of watches steadily increase after each save. I've never worked with watches myself before, but unless this is picking up on build artifacts from RLS (which it shouldn't since I have ignores on that basically everywhere), I would suspect this is some kind of leak.

This shouldn't happen. First step is to try to reproduce the problem in a test project.

**Comment by nicks** [comment]
to be clear, is this on macos or linux?

**Comment by dotellie** [comment]
In my case, it's Linux :penguin:

**Comment by jazzdan** [comment]
I've got a repro case! It's very alarming. On Linux:

```
$ git clone --branch dmiller/add-tiltfile https://github.com/jazzdan/Rocket.git
$ cd Rocker
$ code .
# change `example/hello_world/src/main.rs`
# tilt starts a rebuild and then crashes with the inotify event queue overflow error
```

**Comment by nicks** [comment]
this should be fixed in the next release (by pr https://github.com/windmilleng/tilt/pull/1865)
