### ISSUE TITLE
Flag to disable automatic opening of WebUI 

### ISSUE THREAD

**Issue by mariavivanco** [windmilleng/tilt#1821]
Every time Tilt starts up, it opens a new tab for the web UI even if there is a Tilt tab open already as reported by @dotellie in the #tilt channel:
> I have the tab permanently pinned in Chrome so I don't really want another one to open 
 
Edit: Tilt should have a flag that can disable the automatic opening of new Tilt WebUI tabs.

**Comment by dotellie** [comment]
This isn't really a bug as much as it's a limitation of current browsers. Tilt detects that a tab is already open but that's only if Chrome is still actively keeping that tab alive. As an example, if I exit Tilt, keep my computer on during the night with another tab open in Chrome, Chrome will decide that the Tilt tab isn't important anymore and put it to sleep which means that Tilt can't detect that a tab is already open, causing it to open another tab. What really is needed here is just a flag to disable the automatic opening outright :wink:

**Comment by nicks** [comment]
This has been available for a while as `--no-browser`

**Comment by tumregels** [comment]
Just checked on `v0.18.9` the flag `--no-browser` is not there

```
$ tilt version
v0.18.9, built 2021-02-12
$ tilt up --no-browser
...
unknown flag: --no-browser
```

**Comment by nicks** [comment]
Hi @tumregels ! We removed the flag because Tilt doesn't open a browser by default anymore. Is there something else you were looking for?

**Comment by tumregels** [comment]
Hi @nicks. Sorry, just realized that can connect to `http://localhost:10350` after `tilt up` with using space.

**Comment by kahirokunn** [comment]
How can I rather open the browser automatically now?
Thx 🙏
