### ISSUE TITLE
Tilt understands service dependencies

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1846]
There are situations where services need to start in a specific order: redis needs to start before service A, or service B opens a persistent connection to service C. Users should be able to express these dependencies in Tilt to ensure that they are started in the correct order.

Open questions:

* Is it sufficient to only worry about this on start, or are there scenarios where, if service A depends on service B, that we need to restart service A if service B changes?
* Is it more ergonomic to just make Tilt start the services in the order you define them, or is it better to make an explicit dependency graph with some new syntax feature?

**Comment by zmarouf** [comment]
Hi @jazzdan!

I hit that issue in #1844.
For this specific use case it would've have been enough for me to declare that my resource depends on another —— maybe via a k8s annotation?
E.g `tilt.dependsOn: service.mysql.mysql, deployment.kube-system.sealed-secrets-controller, natsCluster.nats.nats-cluster`

If nats-cluster is missing the deployment is stuck until it works (or it times out?)

Tilt could also compute the dependency graph to expose it to users in a different tab.

Tilt could then restart all downstream dependents or have users opt-in with a different annotation.

I'm looking forward to what you come up with :)

**Comment by landism** [comment]
https://docs.tilt.dev/resource_dependencies.html

The various `_resource` Tiltfile directives now have a `resource_deps` arg for this purpose. It's possible there are more, related use cases that come up, but going to call this issue done and track any new use cases that are requested in new issues.
