### ISSUE TITLE
"error streaming ___ logs" spam after pod terminates

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#1862]
Repro:
1. In [tilt.build](https://github.com/windmilleng/tilt.build), `tilt up`
2. Wait for all the services to be green
3. Edit [deploy/serve.yaml](https://github.com/windmilleng/tilt.build/blob/master/deploy/serve.yaml): remove the 'e' from the end of blog-site's spec.selector.matchLabels
4. Wait a few minutes

Observed:
unending spam that tilt cannot find the pod:
```
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
Error streaming blog-site logs: pods "blog-site-84f5dd4c8c-nqcrq" not found
```

Expected:
there's no more pod so there's nothing to display

**Comment by maiamcc** [comment]
🤔 @landism those repro steps didn't work for me...

**Comment by landism** [comment]
This still repros for me every time.

My understanding of the issue is:

When I apply the broken yaml, k8s terminates the existing pod, leaving the manifest with no running pod.

Our pod watcher is implemented as a `chan *v1.Pod`. All pod change notifications come in this form, including deletions. We have no code anywhere that allows for removing a pod from a manifest's podset when the pod disappears.
Thus, the pod disappears, the log watch ends, and every time we call `PodLogManager`'s `OnChange`, it says "hey, we have a pod we're not watching, let's start watching it!", and then immediately fails.
