### ISSUE TITLE
Allow Tilt to reuse k8s objects from previous executions of Tilt

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#1897]
Sometimes a service has a long startup time. At the moment, Tilt injects various labels into any k8s objects it deploys, which means any time a user starts Tilt, it restarts all of its workloads, even if nothing has changed, which can result in the user unnecessarily waiting for a long startup time. There is currently no workaround for this.

(any solution might involve much of the same work as #1668)

**Comment by maiamcc** [comment]
@nicks looks like the work you've been doing recently will resolve this -- can you close this issue when your stuff is verified?

**Comment by nicks** [comment]
Yep, this should work now
