### ISSUE TITLE
Add support for helm dependencies

### ISSUE THREAD

**Issue by benmathews** [windmilleng/tilt#1913]
If a helm chart has any dependencies specified in the requirements.yaml file, they are not installed when running the tilt up command. This use case should be supported.

**Comment by benmathews** [comment]
Modifying the tiltfile to the below works, but it seems the helm command should work.

k8s_yaml(local('helm template path/...'))

**Comment by nicks** [comment]
Thanks for the report! Ya, this is wrong, Tilt should include the helm requirements. 

I think we screwed this up when we were trying to exclude the tests in https://github.com/windmilleng/tilt/pull/1619

Let me poke around a bit and see what APIs helm exposes for this

**Comment by benmathews** [comment]
Thanks for the fast response. Impressive.
