### ISSUE TITLE
A slightly hard to debug error message

### ISSUE THREAD

**Issue by chuckha** [windmilleng/tilt#1918]
I was using tilt to install a multiple big piles of k8s yaml onto a cluster when I encountered an error:

`invalid reference format: repository name must be lowercase`

I didn't quite understand what this was because there was so much yaml output, but eventually realized that some yaml I was trying to install was broken.

I would have liked this error to tell me which object failed to install as I was installing about 30 objects at the same time.

## Reproduce:

1. Create a `Tiltfile` with these contents:

```
project = 'hello tilt'

yaml_str = """
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - image: IMAGE_URL
"""

k8s_yaml([blob(yaml_str)])
```

2. run `tilt up`

This might seem obvious when there is only one object, but it was fairly confusing to get this error in the middle of many objects being installed.

**Comment by landism** [comment]
oy, yeah, this output leaves much to be desired
```
Starting Tilt (v0.9.3-dev, built 2019-07-24)…
Installing Tilt NodeJS dependencies…
Beginning Tiltfile execution
invalid reference format: repository name must be lowercase
Starting Tilt webpack server…
```
