### ISSUE TITLE
auto-scrolling should stop when the user scrolls up

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#1935]
in the #tilt channel, Chuck reported that he was using the Tilt logs view. The service has lots of logs. He's using Safari

When he scrolled up, the UI would autoscroll back down to the new logs.

Expected behavior: when you scroll up, the UI should stop autoscrolling

I have not been able to confirm this behavior, but I do not have my Mac with me today.

**Comment by jazzdan** [comment]
Hmm, it works for me on Safari.

**Comment by jazzdan** [comment]
I'm going to see @chuckha in person tomorrow and I'll try to figure out what's going on.

**Comment by chuckha** [comment]
does not reproduce when dan is watching

feel free to close, thank you for looking into it !

**Comment by maiamcc** [comment]
Multiple other folks have reported this :-/

from #tilt :
```tmc Yesterday at 4:00 PM
running 0.10.7 — if a container is spewing a ton of output the web view becomes basically unusable since contents will scroll off the page
9 replies

maia  21 hours ago
oh dear.
a. is this behavior new, or were you experiencing it before you updated?
b. what browser/version are you on?
c. so when you scroll up even just a bit, the auto-scroll behavior is SUPPOSED to turn off so that you stay looking at the point at the logs you’re currently at. I assume that’s not the case for you? (I.e. if you scroll up a bit, logs continue spewing/scrolling you back down?)

Matt Brown  17 hours ago
I have the same browser behavior. auto-scrolling continues even when you scroll up.
v. 0,10,6
Firefox browser (edited) 

maia  1 hour ago
:disappointed: :disappointed: :disappointed:

maia  1 hour ago
@dmiller did you say you could replicate this?

maia  1 hour ago
also @Michael Hatch iirc you were seeing this autoscrolling bug — what browser are you on? (are you still seeing it?)

Michael Hatch  1 hour ago
chrome

dmiller  1 hour ago
I was able to replicate it sometimes on Firefox

dmiller  1 hour ago
maybe it has to do with the rate of messages

Matt Brown  5 minutes ago
I also noticed it when the messages were scrolling super fast
```

**Comment by landism** [comment]
this might be picking nits, and is really a technical distinction between two cases that look pretty much the same to users, but I think it's at least worth improving clarity among Tilt devs:
1. autoscrolling firing incorrectly - autoscrolling is where the UI modifies the scroll position to make the last line of the log visible. The scrollbar changes position to the bottom.
2. The contents of the scrollback buffer changing - when the scrollback buffer hits its limit, we kick out old lines to make room for new. This means that the user could have scrolled up to put the scrollbar halfway from the top, and the scrollbar is not moving, but the log lines that are 50% of the way through the buffer keep changing.

AFAIK we have no known bugs of case (1) above. (2) is definitely a problem, and easily reproducible by changing a service to log a lot.

I don't know if Chuck's problem is (1) or (2) above, but the reports in the previous comment definitely sound like (2).

**Comment by kvokka** [comment]
Still getting the same with Firefox.
Later may test with other browsers, if it can help somehow

**Comment by nicks** [comment]
ok, i think @landism has some ideas of simple things to try, to at least try to separate out class (1) problems from class (2) problems so it's easier to see which bucket you're in

**Comment by nicks** [comment]
the new version of tilt should have a fix that doesn't entirely fix the issue, but at least makes it much less jarring

**Comment by kvokka** [comment]
Thank you @nicks ! 👍
