### ISSUE TITLE
Surface stdout & stderr from `local`

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1957]
Joeb:
> I do wish there was a little more output printed when commands fail in `local()`

> I think if stdout & stderr went somewhere that I could read from the tilt UI it would be wonderful

**Comment by jazzdan** [comment]
@chuckha also asked for this

**Comment by nicks** [comment]
as far as I know, we do this already. here's the Tiltfile output from running https://github.com/windmilleng/tilt.build. Note that `local: make api` output

![Screenshot from 2019-08-01 13-01-35](https://user-images.githubusercontent.com/278641/62312606-961d3c00-b45c-11e9-80fe-a6d817a2c941.png)

Is there something else people are hoping for or expecting?

**Comment by joeblubaugh** [comment]
I think you may actually do so - I think that tool that I was running to generate K8S YAML just has *very bad* stderr messages.

**Comment by chuckha** [comment]
I realized my development tool that was generating yaml was entirely replaced by a for loop in a Tiltfile.

I'm in the same boat as @joeblubaugh and it would be fine from my perspective to close this issue.

**Comment by nicks** [comment]
Going to close this issue, but there may be some future feature enhancements that make it easier to figure out where `local()` stdout/stderr is coming from, and when the stdout/stderr is just bad
