### ISSUE TITLE
Keep output of tilt UI after tilt server goes away

### ISSUE THREAD

**Issue by chuckha** [windmilleng/tilt#1989]
Sometimes my tilt goes into a rebuild loop (because I'm bad at .dockerignore syntax) and I don't want it to keep cycling forever, but I'd rather kill the tilt instance and read/inspect the logs at my own pace, maybe come back to it later, see what the problem was and fix it. However, if I kill the tilt program the UI and all of my logs disappear.

Two solutions I've thought about that would work for me would be to not have the UI erase my logs and say it's trying to reconnect and only erase my logs when I've reconnected. At that point, I'm in a new tilt-run and don't care about my previous run so it's ok to hide/delete/remove my logs.

The other solution I was thinking was: tee tilt output to a separate log file and let me inspect it later.

Feel free to disregard those options, those are just two things I thought of that would be useful for me when I stop my infinite tilt-loop to debug what I've messed up.

**Comment by nicks** [comment]
Good idea! Ya, there are a few simple things we can do here to make this better

**Comment by nicks** [comment]
fixed! Now it will show a warning bar until it reconnects
