### ISSUE TITLE
Better error messaging about single pod support for LiveUpdate

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1997]
Spent a load of time trying to help a user debug a LiveUpdate issue where they consistently got "don't have info for running container" error and fell back to a full image build.

The issue was that they were running >1 replicas, and when trying to get ContainerInfo for multiple pods at once, [we silently bail](https://github.com/windmilleng/tilt/blob/e2f4ad8c83e826c92312e8fba309028b748e0f08/internal/store/build_result.go#L256) instead of at least raising a useful error message.

**Comment by maiamcc** [comment]
Re-opening this ticket because, while we DO log a descriptive error message when we hit this case, it can quickly scroll off-screen. (e.g. @MattHodge recently missed this message.) We should consider surfacing this error as an Alert -- if the user is trying to live update multiple pods at a time, and LiveUpdate is failing b/c of that, they presumably want to know.

**Comment by rhyek** [comment]
Any plans to support replicas > 1? It is sometimes useful (and depending on the type of service actually required) to test horizontal scaling during development and it would be great to avoid frequent full rebuilds.
