### ISSUE TITLE
Proposal: Support K3D

### ISSUE THREAD

**Issue by matthiasak** [windmilleng/tilt#2001]
Rancher's k3d project recently introduced a similar cli feature to KIND for syncing container images to the "in docker" k8s instance. You can see this in the v1.3.0 release here: https://github.com/rancher/k3d/releases/tag/v1.3.0.

Would a similar set of commits to https://github.com/windmilleng/tilt/commit/831ddd8bd7ce9c108de16088d5a160a953fd4561?diff=split still be feasible to provide support for pushing images to k3d?

**Comment by nicks** [comment]
Sure! Is this something you were interested in contributing? Should be pretty straightforward

**Comment by nicks** [comment]
One side note: the strategy that KIND and k3d currently use for syncing images is to dump the image on disk and import it. This is good for local dev but not amazing. 

We still tend to recommend things like docker-for-mac or microk8s. They run an image registry in-cluster, and the registry protocol means that you only push the layers that change. 

Just want to set expectations. We're hoping that KIND and k3d add easier in-cluster registry management.

**Comment by nicks** [comment]
We have a guide for this now!
https://github.com/windmilleng/k3d-local-registry

**Comment by nicks** [comment]
(basically, if you set your k3d cluster with the script provided there, Tilt will find the local registry and use it for pushing. This is much faster than syncing the images with the CLI)
