### ISSUE TITLE
`tilt up` terminates if k8s unauthorised

### ISSUE THREAD

**Issue by aidansteele** [windmilleng/tilt#2062]
Scenario:

* I was following the [tutorial](https://docs.tilt.dev/tutorial.html).
* I added `k8s_yaml(local('helm ...'))`
* tilt advised I add `allow_k8s_contexts('<my context name>')`
* I added that line to my Tiltfile
* The tilt web UI appeared to "crash" and get stuff on "Reconnecting..."
* The `tilt up` long-running terminal program terminated with error: `Error: Error watching k8s events: could not set up k8s client: unable to fetch API Group Resources: Unauthorize`
* I re-run `tilt up` once I have authorised.
* The `tilt up` UI *briefly* shows an informative error message and then terminates, clears the screen and shows `Error: Error watching services. Are you connected to kubernetes?: Services.WatchFiles: unknown (get services), Reason: Forbidden, Code: 403`
* Dev gets flustered as they wish they could read that informative message for a little longer!

I managed to snag a screenshot of the brief error message before it disappeared and have attached it. I understand there's only so much tilt can do when it doesn't have permissions to access a fairly locked-down k8s cluster, but it could be helpful if the error message wasn't so brief 😄 

Thanks for what looks like a very promising tool!

<img width="1378" alt="Screen Shot 2019-08-15 at 10 23 19 am" src="https://user-images.githubusercontent.com/369053/63064888-e7dac180-bf46-11e9-8b6e-6efcc4d6fea9.png">

**Comment by nicks** [comment]
Thanks for the report! Ya, we need to make that error stick around better.

Do you also need help figuring out why the "Error watching services" error is happening? It was unclear if you had figured out how to resolve that, or if this issue is just about the broken error UX. If you run `kubectl get services` or `kubectl get services -w` locally, does that work?

**Comment by jazzdan** [comment]
Should be fixed now, thanks for the report @aidansteele!
