### ISSUE TITLE
Feature request: Rerun

### ISSUE THREAD

**Issue by chuckha** [windmilleng/tilt#2068]
Normally, I don't ever have to rerun anything, Tilt just knows and that's awesome! However, today my disk filled up when tilt was building a docker image. So I went off and cleared some space and now I'd love to have a way to rerun the docker-build action without having to quit tilt or make an empty patch to some file that would trigger a rebuild.

here is a link to my workspace snapshot so you can see.

https://alerts.tilt.dev/snapshot/AY6wrdULbLCfixQODzU=

**Comment by jazzdan** [comment]
This seems related to some of our manual update control work. What do you think @hyu?

**Comment by tmc** [comment]
I was going to open an issue about rebuilding via the cli in manual trigger mode -- it sounds like this would address that desire.

**Comment by maiamcc** [comment]
Closing this in favor of #1012.
