### ISSUE TITLE
Preview Pane for "All" should show links to resource previews

### ISSUE THREAD

**Issue by hyu** [windmilleng/tilt#2069]
The Preview Pane for "All" should show a list of links to all available endpoints. Instead, it's currently showing a misleading error "No resource found at /preview."

Aidan Steele flagged this issue in [K8s #tilt channel](https://kubernetes.slack.com/archives/CESBL84MV/p1565914036230100) on 2019-08-15:

> i might have missed this in the docs somewhere (though i did check a few pages!). when i click preview, i get No resource found at /preview - what do i need to do in order to get something to render? my app's logs indicate that it's not even receiving a request to /preview

### Page should look like this:

<img width="1677" alt="2019-05-02 - Web - ALL Preview" src="https://user-images.githubusercontent.com/20349/63180577-93a21100-c01c-11e9-8aaf-86152a6b87a3.png">

**Comment by nicks** [comment]
hmmm this feels like it broke recently
