### ISSUE TITLE
Way to clean filepaths in Tiltfile

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2098]
Requested by kavirajkanagaraj in #tilt:

> does anyone else miss helper function similar to Go’s filepath.Clean("//hello///how/are/you/") in Tiltfile? or python’s os.path.realpath()
> Its mainly combining different paths. We have multiple repositories for source code, helm charts and dockerfiles, so we just accept root of organisation and append different paths. The pain point is it may endup with multiple trailing slashes which causes problem particularly sending docker context. So good to have some helper function there!

It might be nice if there was some way to make it easier for external contributors to contribute to these functions.

See also #1980

**Comment by kavirajk** [comment]
Thanks @jazzdan for creating the issue!. I think I can help here!

**Comment by nicks** [comment]
this got raised in the #tilt channel again

As a meta-issue, I wonder if we should also have a contributors guide on how to write tiltfile built-ins in Go (in addition to any guides on how to write extensions in starlark). They should be pretty easy now, e.g. https://github.com/windmilleng/tilt/blob/master/internal/tiltfile/os/os.go

**Comment by fentas** [comment]
:+1: For me, I build dynamically build object and pass it `docker_buld` like
```
docker_build('image/%s' % name, **_build)
```
within `_build` following attrs look like
`docker_file ~ '/home/user/test/../other/folder'`
`context ~ '/home/user/test/../other/folder'`

Half a year this worked. But now this will fail only for the attr `context` as it has not the right for the container build. So this would work, though.

`docker_file ~ '/home/user/test/../other/folder'`
`context ~ '/home/user/other/folder'`

Now I use
```
def realpath(path):
  return str(local('realpath -L %s' % path, True)).rstrip()
```

which I do not like for two reasons
1) it's quite Linux specific
2) it will output what it does regardless of `quite == True`.
