### ISSUE TITLE
`helm()` should watch files in `requirements.yaml`

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2114]
As it says on the tin. It's confusing that Tilt doesn't understand this.

**Comment by digger18** [comment]
How can we raise the priority on this?

**Comment by jazzdan** [comment]
Hi @digger18,

I'm raising the priority on this. Should be getting a fix in soon, thanks for your patience!

**Comment by jazzdan** [comment]
Hey @digger18, can you send me an example of the kind of chart dependencies you want to support? It seems like there are many ways to do it (local, remote, etc) and I want to make sure we support your use case.

**Comment by digger18** [comment]
My requirements.yaml is built with local subcharts.

Example link:
file://../subcharts/example_subchart
