### ISSUE TITLE
Web UI resets horizontal scroll to far left

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#2155]
repro:
deploy a service that logs a 300-char word (e.g., `strings.Repeat("foo", 100)`)
in the web ui, scroll to the right to view the later part of the string that appears off-screen

observed:
the UI regularly scrolls back all the way to the left
(I haven't looked into it, it was not immediately clear to me what triggered this scroll. Sometimes it'd happen quickly and sometimes it'd take 10 seconds.)

expected:
A couple of outcomes that would be vastly better:
* tilt simply doesn't reset the scroll back to the left
* tilt performs line wrapping so that scrolling right isn't necessary in the first place (this is what the console UI does, and I thought what the web UI already did)

**Comment by landism** [comment]
After looking into it a bit more:

If you log `strings.Repeat("foo ", 100)` (note the space after "foo"), Tilt does perform line-wrapping, which would prevent the need to scroll in the first place, except it performs the wrapping at the edge of the window under the sidebar, so you can't read the stuff that's under the sidebar. You can also collapse the sidebar to see most of it, but a few columns will still disappear under the collapsed sidebar, e.g.:
![image](https://user-images.githubusercontent.com/7453991/64372165-40562980-cff0-11e9-91a3-2915d53ac019.png)

So, perhaps the two things to do for this bug are:
1. Change web UI line-wrapping so that it can perform a wrap in the middle of a work
2. Change web UI line-wrapping so that text doesn't get written under the sidebar.

**Comment by nicks** [comment]
fixed by https://github.com/windmilleng/tilt/pull/2158
