### ISSUE TITLE
Docker-for-mac installation guide is outdated

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2193]
Previous versions of k8s for mac use context `docker-for-desktop`, but the latest (2.1.0.2) docker for mac use `docker-desktop` context. This is minor change, while much more significant is, that now it does not contains the  information about the daemon.

``` bash
Starting Tilt (v0.10.7, built 2019-09-11)…
Error: NewDockerServerVersion: Cannot connect to the Docker daemon at tcp://192.168.99.101:2376. Is the docker daemon running?
```

**Comment by maiamcc** [comment]
Hi @kvokka - good point about [the mac install instructions](https://docs.tilt.dev/install.html#on-macos), will fix that.

As for the other error -- you updated to Docker `2.1.0.2` and now Tilt can't find the Docker daemon? can you provide the following:
- `tilt doctor`
- `docker --version`
- `echo $DOCKER_HOST`
- `echo $DOCKER_API_VERSION`

**Comment by maiamcc** [comment]
cc @nicks who was maybe looking into something similar?

**Comment by kvokka** [comment]
Thank you for a cush a quick response!

Here is all requested information:

```bash
$ tilt doctor
Tilt: v0.10.7, built 2019-09-11
System: darwin-amd64
---
Docker
- Host: tcp://192.168.99.102:2376
- Version: 1.39
- Builder: 1
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.15.2
---
Thanks for seeing the Tilt Doctor!
Please send this info along when filing bug reports. 💗

$ docker --version
Docker version 19.03.2, build 6a30dfc

$ echo $DOCKER_HOST
tcp://192.168.99.102:2376

$ echo $DOCKER_API_VERSION  # it does not set!

```

Feel free to ask any details and thank you for a great tool!

**Comment by maiamcc** [comment]
Hmm, Tilt isn't picking up that you've set your k8s context to docker for mac -- it still thinks you're using minikube, and presumably it'll try to use the minikube docker daemon. if you correctly set your kubecontext to docker for mac and try `tilt doctor`/`tilt up` again, does stuff work?

**Comment by kvokka** [comment]
After the previous message i switched back to minikube for a while, and now trying again Tilt works as it should.
The only special action which i did was restart of the mac (for another thing), but maybe it helps.

Not it fixed and I can not reproduce the issue.

@maiamcc Thank you for your help!

**Comment by nicks** [comment]
Hmm... sounds like you were able to figure out the problem! Yay!

For reference: if you have the DOCKER_HOST env variable set, Tilt will respect that:
https://docs.tilt.dev/faq.html#q-how-do-i-tell-tilt-to-build-my-images-with-a-remote-docker-server
In this case, it sounds like you had Tilt configured to talk to the Docker server in minikube.
