### ISSUE TITLE
`allow_k8s_contexts` doesn't protect against local commands that touch k8s

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#2194]
#1995 was implemented to provide users assurance that they wouldn't accidentally mutate their production cluster.

If a user has `local` commands in their Tiltfile that mutate their cluster (e.g., `local('helm install ...')`), those commands will still execute.

This is because the implementation is: execute the Tiltfile, then verify the k8s cluster in use is allowed.

Some possible solutions:
* Require `allow_k8s_contexts` to happen at the start of the Tiltfile, and make it cause immediate failure.
** This would mean it couldn't take input from a config file (e.g., I've renamed my staging cluster from some horrible GKE name to 'staging', and maybe I want to specify that in a config)
** "must be first" isn't really a scalable solution - we might want similar rules for `enable_feature` or `k8s_resource_assembly_version` - maybe "must preceed any `local` directives"? Are there any other directives we need to worry about? Do we care that this precludes, e.g., using `local` to get the context name from kubectl?
* Do it in two passes - first execute the Tiltfile, skipping any `local` executions to get `allow_k8s_contexts`, validate, then re-execute.
** Aside from the issue above of this precluding `local` being used for control flow / input to `allow_k8s_contexts`, it just seems like a huge can of worms for everything to worry about maybe happening twice.

**Comment by nicks** [comment]
i understand the *must be first* requirement, but it seems premature at this phase. It seems like the first step is to make `allow_k8s_contexts` fail immediately?

**Comment by landism** [comment]
> i understand the must be first requirement, but it seems premature at this phase. It seems like the first step is to make allow_k8s_contexts fail immediately?

The change isn't really to make `allow_k8s_contexts` fail immediately - it's to make Tiltfile execution fail as soon as we're sure we've seen any existing `allow_k8s_contexts` directives.

Presumably the common case is that a Tiltfile contains no `allow_k8s_contexts` directive, in which case any changes to that builtin's behavior would have no effect.

The "must be first" requirement is key because it allows us to be sure we've seen any existing `allow_k8s_contexts` and correctly enforce context requirements at the start of Tiltfile execution, before any risky `local`s have executed.

**Comment by maiamcc** [comment]
Oof yeah given that we just made a blog post about how this was safe now, I feel weird leaving this behavior around. @landism can you take a bit to estimate a fix, and then we can decide how to proceed?
