### ISSUE TITLE
no documentation for dc_resource method

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2208]
`servantes` demo project contains the line

```
dc_resource('fortune', image='fortune_for_dc')
```

But this command is not documented at https://docs.tilt.dev/api.html#api.k8s_resource

**Comment by nicks** [comment]
Thanks for the report! 

@maiamcc do you remember what this is for and if it still works?

**Comment by maiamcc** [comment]
Oh shoot yes this thing! It's the Docker Compose equivalent of [`k8s_resource`](https://docs.tilt.dev/api.html#api.k8s_resource) -- you use it to configure a Docker Compose resource, but the functionality is currently kind of limited:
- `image` argument used to associate an image with your DC resource, though in most cases this is done automatically. (But this arg is still require, which is a bug! 😅)
- `trigger_mode` - configure [how the service updates (automatically or manually)](https://blog.tilt.dev/2019/06/19/new-in-tilt-fine-tune-how-your-services-get-updated.html)

In future, you'll be able to set things like port forwards with this function.

Great eye, @kvokka -- I'll update the docs and fix the demo app/required arg behavior sometime this week!
