### ISSUE TITLE
add options for `helm` function

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2209]
## Feature request

Almost every run of the helm chart require providing value files, the name of the chart and the namespace . This require to use `local` function instead of `helm` and make `helm` function almost useless with real world examples.

**Comment by nicks** [comment]
thanks! Ya, it should be straightforward to add new arguments. Let me see what we can do here

**Comment by nicks** [comment]
Fixed in #2218 . The arguments should be available in the latest tilt release
