### ISSUE TITLE
Error loading external tilt file if command is before allow_k8s_contexts

### ISSUE THREAD

**Issue by omrikiei** [windmilleng/tilt#2248]
I have a Tiltfile with various helper functions(none of them is k8s cluster related) and it is being loaded in my main Tiltfile. tilt fails because this load line is evaluated before the line with allow_k8s_contexts... the configuration has the relevant cluster configured

relevant from mail tiltfile:
``` 
load("helpers.tilt", "helm_blob", "has_service", "username")
 # Read config
 conf = read_json('config.json', {})
 services = read_json('services.json', {})

 # Set default registry
 default_registry(conf.get('default_registry', TAP_REGISTRY))

 # Limit runtime to specific contexts(avoid changes in prod or qa)
 allow_k8s_contexts(conf.get('allowed_context', []))
```

And the error I get:
```
    ERROR:
         /Users/omrieival/dev/TapingoDevEnv/Tiltfile:4:1: in <toplevel>
       Error: cannot load helpers.tilt: Stop! 'dev.k8s.tapingo.com' might be production.
       If you're sure you want to deploy there, add:
       allow_k8s_contexts('dev.k8s.tapingo.com')
       to your Tiltfile. Otherwise, switch k8s contexts and restart Tilt.
```

**Comment by jazzdan** [comment]
Hi @omrikiei, sorry about this cryptic error message. You should be able to work around this by moving the `allow_k8s_contexts` before the `load` in your script. Or do you need to run the `load` before you can execute the `allow_k8s_contexts`?

I'll definitely fix the error message though, that's pretty confusing.

**Comment by jazzdan** [comment]
I'm going to close this for now given the new error message, let me know if it's still an issue for you @omrikiei

**Comment by omrikiei** [comment]
Hi @jazzdan, that's what I did for a workaround and it works :), however moving forward I think there shouldn't be a constraint or coupling between unrelated statements in the Tiltfile. Imagine a scenario where a user employs the config loading function that initially loads the allowed k8s contexts from a helper tilt file and then sets the contexts based on that..

**Comment by jazzdan** [comment]
Hi @omrikiei, hear you loud and clear. Let me create a separate bug for that so we can think through some solutions.

**Comment by jazzdan** [comment]
Created #2269
