### ISSUE TITLE
Job does not include the sync files on start

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2266]
## Bug

Given
```
# Tiltfile
docker_build("api", "api", dockerfile="api/Dockerfile", live_update=[
    sync('./api/src', '/app/src'),
  ])
```

```
# Dockerfile
FROM node:10

ADD package.json /package.json
RUN yarn install --quiet

CMD ["yarn", "run:dev:docker"]
```

In simplified version of Dockerfile, as you can see, there is no code.

The idea is, that it should be provided by sync.

But in fact it doesn't and container crushes. When you add `COPY src src` to `Dockerfile` everything works. But we need it only for startup process, because container starts before the sync. Maybe there is any possibility to run code-free containers, like in the above example?

Thank you!

**Comment by jazzdan** [comment]
Hey @kvokka, we think of `live_update` as an optimization on type of existing, working Dockerfiles to make them faster in development contexts. Your setup should still work, if slower, if the `live_update` got removed.

Why do you want to have a Dockerfile that creates an image that has no code? Or is this an existing Dockerfile that you use in a different setup?

**Comment by nicks** [comment]
One pattern we've seen work well for this is to have two Dockerfiles, an image for the package.json deps and an image for the source. See: https://docs.tilt.dev/dependent_images.html

**Comment by kvokka** [comment]
Thank you for the responses!

I'm familiar with base image pattern, but this idea can go further. Facing the problem from #2265 i tried to use the hack with NFS which was handy with `docker-compose` utility. For `docker-compose` it was used to get some speed improvement with docker-for-mac, and it reduced for ~20-25% time of the test suite run. The idea is to use the image only as the holder of the dependencies or utilities and attach the code from another source (NFS volume from previous example).

Switching back to this issue i tried to use `sync` function to substitute the missing code (what for to copy it to the image, if we syncing it anyway?)

If the usage in this way is not allowed - it is definitely ok and we can live with it. In this case this issue bought some new nuance in the docs :)

**Comment by jazzdan** [comment]
A number of people have written in with this confusion. I think we should try to change something about the docs to address it.

**Comment by maiamcc** [comment]
Closing this in favor of docs request #2390. TY for your report!
