### ISSUE TITLE
Manage Helm volume information

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2274]
## Question/Feature request

Now, running `k8s_yaml(local('helm template ./mysql'))` you will get installed `mysql` on `tilt up` and removed `mysql` on `tilt down` with all volume information. So, on every run- new system. Ok, this pattern may be useful.

But what if I want to install mysql with Tilt, and do *not* remove the data at the end? Using `local('helm template ./mysql')` i will get installed `mysql` on `tilt up` and *installed `mysql` on `tilt down`. It works, but it is not pretty + you need to wait until `mysql` update itself on `tilt down`, anyway after this process you will have `mysql` service still running.

Going further, with `helmfile` you'll get the bundle of the utilities with this behavior.

The simple solution is to run `helmfile` outside of Tilt. But is it the best option? Maybe there is some hack which cover the use case like this?

Thank you!

**Comment by jazzdan** [comment]
Hi @kvokka, thanks for the example! I'm going to close this as a duplicate of https://github.com/windmilleng/tilt/issues/1699
