### ISSUE TITLE
Job with custom image doesn't run when image is updated

### ISSUE THREAD

**Issue by hyu** [windmilleng/tilt#2285]
A Job with a custom image from Tilt runs fine the first time. But not later when the image is updated due to a change of the local files.

@tsloughter reported this issue in [#tilt Slack](https://kubernetes.slack.com/archives/CESBL84MV/p1569941665139600):
> so the job issue is, I think, related to how it has to sync files which are then copied to a volume that is shared between 2 containers in the pod. This is how I get migration sql files from the project to the container that runs flyway.

### Repro details:
- [Tiltfile](https://github.com/adoptingerlang/service_discovery/blob/buildkit-cache/Tiltfile)
- [Base job YAML](https://github.com/adoptingerlang/service_discovery/blob/buildkit-cache/deployment/base/flyway-job.yaml)
- [Base Job YAML - patched for Tilt](https://github.com/adoptingerlang/service_discovery/blob/buildkit-cache/deployment/overlays/dev/flyway_job_patch.yaml)

Change a migration file under apps/service_discovery_postgres/priv/migrations

The job reruns but Flyway says there are 0 migrations (not just no new ones, but none at all) under /flyway/sql.

**Comment by tsloughter** [comment]
And going to remove the `live_update`. Since the container doesn't keep running when used as a job that is pointless and is unused.
