### ISSUE TITLE
Change IP address that webserver binds to

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#2321]
From Matt Brown on #tilt:
> Is there a way to have tilt bind to 0.0.0.0 instead of just localhost?
> I want port 10350 to be accessible from another machine.  In my case, I just want to see the log messages on my iPad while running tilt on my laptop.
> So I just want the tilt webserver to bind to 0.0.0.0

**Comment by gowabash** [comment]
THis would just allow other members of my team (and my iPad) to be able to see log messages.  My assumption is that is just the web interface to the logs.  If other operations can be performed over the port, than maybe it's not a great idea.

**Comment by landism** [comment]
> THis would just allow other members of my team (and my iPad) to be able to see log messages.

Do you want them to be able to watch in realtime? Is it possible that [snapshots](https://docs.tilt.dev/snapshots.html) meet your need?

**Comment by gowabash** [comment]
Snapshots work for one offs, but having the logs available to both while pairing would be super helpful. I can always use ngrok to get past it, so urgency is low.

**Comment by andymartin-sch** [comment]
This would also be helpful for the use-case where developers are launching Tilt on a remote server and want to watch the browser-based Tilt UI from a web browser running on their local machine.
