### ISSUE TITLE
pushing to microk8s registry fails with ipv6

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#2369]
Repro steps:
1) Install microk8s with a private registry and make it your default cluster
2) Create an /etc/hosts where the first localhost entry is ::1

```
::1 localhost
127.0.0.1 localhost
```

3) Run `tilt up`

Expected:
Tilt should successfully push to the registry

Actual:
Registry pushes timeout

This Microk8s bug has more debugging: https://github.com/ubuntu/microk8s/issues/196

I'm not entirely sure whose fault this bug is - if it's a docker bug or a registry bug or a microk8s bug. But we should be able to work-around this by using the ipv4 loopback instead of localhost

**Comment by nicks** [comment]
unfortunately, tagging the image as 127.0.0.1 doesn't work :(

When microk8s gets set up, it lists localhost:32000 as an insecure registry. Using a different tag would mean that we have to use https.

Possibly related to this bug: https://github.com/kubernetes/kubernetes/issues/66766 and is a Kubernetes networking bug. I see kube-proxy hanging onto the [::1]:32000 address, and then not doing anything with it. Interestingly, if I use kubectl port-forward to open a port, it works fine.

**Comment by nicks** [comment]
don't really want to go down a rabbit hole of fixing Kubernetes networking bugs, so for now I'm going to add a quick check that localhost resolves to an IPv4 address, and if it doesn't, emit a warning / don't use the private registry

**Comment by KTAtkinson** [comment]
I don't quite understand what the issue is with using `127.0.0.1` rather than localhost. With the registry running I can execute `docker push 127.0.0.1:32000/<image>:<tag>` just fine. I can also pull the image via docker just fine.

**Comment by nicks** [comment]
@KTAtkinson Re: "disabling `http` is generally not advisable": when you run the microk8s registry, you're running a registry on http, not https. When push/pull from 127.0.0.1, you're pushing/pulling over http, not https. Changing the host from localhost to 127.0.0.1 doesn't change this.

The question you're confused on isn't about http vs https, or about which registry your docker client trusts. It's about which image registries your microk8s cluster trusts. By default, microk8s is configured to trust localhost:32000, but not 127.0.0.1:32000.

**Comment by nicks** [comment]
fixed by https://github.com/windmilleng/tilt/pull/2370

now, if you're on ipv6, tilt won't try to use microk8s' private registry at all, because it simply won't work. This still isn't great, but probably the best we can do right now
