### ISSUE TITLE
Buildkit Dockerfile experimental syntax does not work for child images

### ISSUE THREAD

**Issue by mvgijssel** [windmilleng/tilt#2371]
Using the buildkit [Dockerfile frontend experimental syntaxes](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md) works for regular `docker_build` statements in the Tiltfile but not when using a base image.

For example:

## Tiltfile
```python
docker_build(
    'localhost:5000/child',
    'child',
    dockerfile="Dockerfile.child",
)

docker_build(
    'localhost:5000/base',
    'base',
    dockerfile="Dockerfile.base",
)
```

## Dockerfile.base
```dockerfile
# syntax = docker/dockerfile:experimental
FROM ubuntu:xenial

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y vim
```

## Dockerfile.child
```dockerfile
# syntax = docker/dockerfile:experimental
FROM localhost:5000/base

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y ruby
```

The `base` image will build just fine, but the `child` image will fail with something like:

```shell
ERROR: ImageBuild: failed to create LLB definition: Dockerfile parse error line 26: Unknown flag: mount
got unexpected error during build/deploy: ImageBuild: failed to create LLB definition: Dockerfile parse error line 26: Unknown flag: mount
```

I believe this has something to do with the fact that docker images using a base image will be parsed by tilt to replace the FROM with the tilt tagged image. 

The parsing step removes all comments, including the buildkit header `# syntax = docker/dockerfile:experimental` which results in build failure.

---

### tilt version
```
v0.10.13, built 2019-10-04
```

### docker version
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.13.1
 Git commit:        a872fc2
 Built:             Tue Oct  8 22:01:16 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by maiamcc** [comment]
@mvgijssel ty for the very thorough report! Will look into this now.

**Comment by maiamcc** [comment]
@mvgijssel this should be fixed on master, if you want to build from there -- otherwise, it'll go out in a release sometime this week. Let me know if it works for you!

**Comment by mvgijssel** [comment]
Awesome! What a quick turnaround time 💪. I'll wait for the release and verify if it works! Thanks again ❤️

**Comment by mvgijssel** [comment]
I've build Tilt locally from master and everything works as expected, thanks again!
