### ISSUE TITLE
Tilt should ignore too old resource version errors

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2406]
Tilt can spew error message like the following:

```
github.com/windmilleng/tilt/internal/k8s/watch.go:172: watch of *v1.Pod ended with: too old resource version: 191906663 (191912819) W1021 14:53:11.799222 68992 reflector.go:299] github.com/windmilleng/tilt/internal/k8s/watch.go:172: watch of *v1.Pod ended with: too old resource version: 191906663 (191912819)
```

These should be ignored similarly to how we ignore `watch of *v1.Event` errors in https://github.com/windmilleng/tilt/pull/1820

**Comment by maiamcc** [comment]
@jazzdan when you say we can ignore it like we ignored errors in #1820 -- do you know off the top of your head what flag we'd need to pass? My impression of that other PR is that it only worked b/c the errors we wanted to ignore happened to be of a log level we don't care about.

(This should be easy enough to do via string filtering, but if there IS a cleaner way to do this with flags, I want to know about it!)

cc @landism in case you have knowledge here

**Comment by jazzdan** [comment]
I don't know off the top of my head, no

**Comment by dbentley** [comment]
It might be that we should change k8s.io/apimachinery/pkg/util/runtime:ErrorHandlers to not just log every error.

Cf. https://godoc.org/k8s.io/apimachinery/pkg/util/runtime
