### ISSUE TITLE
Support for docker builds via Azure Container Registry tasks or Google Cloud Build?

### ISSUE THREAD

**Issue by arschles** [windmilleng/tilt#2438]
`docker_build` does `docker build`s locally, but on certain environments it would be helpful to do builds remotely. One could set their local config to [point to a remote daemon](https://docs.docker.com/engine/security/https/), but that's a complicated process and there are other managed options that I would love if Tilt supported. The two that I know of are [Google Cloud Build](https://cloud.google.com/cloud-build/) (formerly [Google Container Builder](https://medium.com/google-cloud/introduction-to-google-container-builder-dbe6645f9421)) and [Azure Container Registry Tasks](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview).

Both of these systems have you send a compressed copy of your code and a `Dockerfile` to the cloud, the service executes the `docker build` command, and finally does the a `docker push`. Importantly, it will only push images to its own cloud-managed registry, not an arbitrary one.

Is there some way I can get this to work today? I think I'd need to somehow specify my cloud auth credentials and that I want to use the cloud builder in the `docker_build` call.

**Comment by nicks** [comment]
Good news! Tilt has a `custom_build` command that lets you use an arbitrary shell command to build your images. Here are the docs:

https://docs.tilt.dev/custom_build.html

does that work?

**Comment by nicks** [comment]
I'm going to close this on the assumption that `custom_build` is an acceptable way to do this, but let me know if you need anything else!

**Comment by arschles** [comment]
@nicks thanks for the reply. `custom_build` would work I think. After I do the build, would tilt still automatically push the image to the standard place in `default_registry`, if that's set?

**Comment by nicks** [comment]
`custom_build` has a `disable_push` parameter that lets you control if Tilt is responsible for doing the push, or if your command is responsible for doing the push.

**Comment by arschles** [comment]
Got it! That's really helpful, thanks @nicks
