### ISSUE TITLE
add --network arg to docker_build

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#2483]
from kubernetes slack:

when developing on a chromebook, it's useful to be able to set the network mode passed to docker build (`docker build --network=host`)

Tilt's docker_build command should accept a network parameter

For now, you can work-around this with a custom build script
https://docs.tilt.dev/custom_build.html

**Comment by windlessuser** [comment]
If this is still needed, I'd like to take this on as my first contribution. :)

**Comment by nicks** [comment]
@windlessuser welcome! ya, a patch for this would be much appreciated. 

Let us know if you need any pointers. The code for processing Tiltfiles is in internal/tiltfile, and the code for calling the docker API is in internal/docker, and we're happy to explain any of the intermediate steps that carry data from one to the other.
