### ISSUE TITLE
docker_compose() function is missing from API docs

### ISSUE THREAD

**Issue by rally25rs** [windmilleng/tilt#2485]
The `docker_compose()` function mentioned here https://docs.tilt.dev/docker_compose.html is missing from the actual API docs https://docs.tilt.dev/api.html

I was hoping to find out if there was a way to compose multiple files, equivalent to `docker-compose -f first-compose.yml -f second-compose.yml`

**Comment by nicks** [comment]
Oops! We'll go ahead and add those monday.

Per https://github.com/windmilleng/tilt/issues/1782, you should be able to do

```
docker_compose(["docker-compose1.yml", "docker-compose2.yml"]
```
