### ISSUE TITLE
Copy + paste from LogPane in to rich text fields doesn't work

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2524]
It appears to be missing newlines

>Seems tilt is styling `<code>` (typically a display: inline element) as display: block such that each line is its own `<code>` element.  Copying and pasting that confuses JIRA's rich text editor which doesn't know how to interpret that.
>
>One way to fix would be to remove display: block from the style being applied to the `<code>`elements and inserting `<br>`s in between each code element

>Confusingly, paste into say Vim works, because it uses the plain-text buffer

**Comment by asottile** [comment]
(I wrote the text above, happy to follow up if you have any questions)

**Comment by landism** [comment]
It also seems unfortunate that when pasting into a google doc, I get white-on-white.

**Comment by landism** [comment]
FWIW, "doesn't work" might be overstating it. I've tried reproing the newline issue in a dozen different web apps, including google docs, gmail, clubhouse, jira, and a bunch of random web rich text editors I found via google, without any luck.

I don't know if it's an issue of a difference in version of JIRA, or Chrome, or MacOS.
