### ISSUE TITLE
Possible to modify web server bind address?

### ISSUE THREAD

**Issue by jdolitsky** [windmilleng/tilt#2537]
I'm attempting to run Tilt in a Docker container, and access the web UI on the host machine by using `docker run -p 10350:10350`.

However, it seems like tilt UI is hardcoded to use `127.0.0.1` as the bind address. Is there any way to configure this to `0.0.0.0` in order to make this work? This issue is pretty well described [here](https://stackoverflow.com/a/52518929).

I'm happy to open a PR to add a new option such as `--addr=<addr>`. Thanks in advance.

**Comment by jazzdan** [comment]
Hi @jdolitsky,

You should be able to start Tilt like this to support your use case: `tilt up --host 0.0.0.0 --port 10350`.

Let me know if this doesn't work for you and I'll reopen this issue!

**Comment by jdolitsky** [comment]
@jazzdan thank you! works

I was getting tripped up, this flag is in `v0.10.18` but not in `v0.10.17` which is what I have on my laptop.. thanks again
