### ISSUE TITLE
PodRestarts cause resource to have yellow dots in web UI, but red dots in terminal UI

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2552]
Repro steps:

1. Cause a container to restart (consider using the [new servantes branch](https://github.com/windmilleng/servantes/tree/dbentley/qod) where 5-10 requests to snack causes the container to crash)
2. Observe that the resource is yellow in the web UI, but red in the terminal UI

It should be visually consistent.

Originally reported [here](https://kubernetes.slack.com/archives/CESBL84MV/p1573681116249000?thread_ts=1573668820.244300&cid=CESBL84MV)

**Comment by andymartin-sch** [comment]
As mentioned in [this thread](https://app.slack.com/client/T09NY5SBT/CESBL84MV), a related issue is:
> I'm seeing Pods that are not yet started due to a running initContainer be gray in the terminal UI but red in the web UI. My opinion is that it should be gray in both places since red implies (to me) that something went wrong.

**Comment by nicks** [comment]
this should be fixed by https://github.com/windmilleng/tilt/pull/3197
