### ISSUE TITLE
Can't dismiss alerts if Tilt is running remotely

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2553]
If you're running Tilt remotely via the [newly added hosts flag](https://github.com/windmilleng/tilt/issues/2321) you won't be able to dismiss dismissible alerts.

This is because we check [if Tilt is being served from localhost](https://github.com/windmilleng/tilt/blob/a7df4bbc22b7d4803d4d966a35ee007d61637bde/web/src/AlertPane.tsx#L47). If it's not, we don't show the dismiss alert button.

If you're running Tilt remotely though, this will return false and you won't be able to dismiss alerts.

I think this needs to be changed to be:

```typescript
if (alert.dismissHandler && !isSnapshot) {
```

**Comment by landism** [comment]
(also worth deleting `isLocal` to reduce the chances of someone else making the same mistake)

**Comment by jazzdan** [comment]
There are some legit use cases but maybe we should make them check if the URL contains `localhost` explicitly.
