### ISSUE TITLE
Ability to set environment variables from Tiltfile

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2564]
Advanced Tilt users want to be able to set environment variables from the Tiltfile, and have those env variables take effect for all subshells (local() calls, etc)

For example, many auth tools use environment variables for auth, and need those environment variables to be periodically refreshed.

A simple thing we could add is implement os.putenv(), and make it so that changes to os.environ change the environment of the whole Tilt process

More discussion in #tilt: https://kubernetes.slack.com/archives/CESBL84MV/p1573694008257200

**Comment by victorwuky** [comment]
@joseph-zhong: This is now available in the latest release. See https://docs.tilt.dev/api.html#modules.os.getenv (and putenv and unsetenv) and https://github.com/tilt-dev/tilt/releases/tag/v0.13.6
