### ISSUE TITLE
Upgrade notification is wrapping

### ISSUE THREAD

**Issue by JimPatterson** [windmilleng/tilt#2580]
I'm currently running v0.10.18, built 2019-11-08 and the notification message is wrapping.  I can't tell if the current version has the problem since the notification won't show for the current.  But I could not find an issue reporting this.

The notification looks like:
![Selection_050](https://user-images.githubusercontent.com/1703168/69147618-6e4ff380-0aa0-11ea-8e8b-560d7afbb18c.png)

**Comment by landism** [comment]
Thanks for the report!
