### ISSUE TITLE
Helm 3 Support

### ISSUE THREAD

**Issue by dolsem** [windmilleng/tilt#2581]
Are there plans to add Helm 3 support? Currently when you specify release name `helm template` command fails with `Error: unknown flag: --name\n`. This is due to https://github.com/helm/helm/issues/6019.

**Comment by landism** [comment]
Thanks for the report!

We definitely want to support Helm 3, but don't yet have an ETA for it.

In the meantime, you can workaround this with, e.g., `local('helm template <name> <chart>')`

**Comment by nicks** [comment]
@jazzdan met some of the Helm maintainers yesterday and got a better impression of what this entails, and we're hoping this won't be too tough

**Comment by jazzdan** [comment]
Fixed in https://github.com/windmilleng/tilt/commit/db669506c9d040a8ffa608dd152c75fed2646ac8.
