### ISSUE TITLE
K8S localhost URL does not work

### ISSUE THREAD

**Issue by jgillich** [windmilleng/tilt#2590]
Quote from the [docs](https://docs.tilt.dev/api.html#api.allow_k8s_contexts):

> 
> Tilt will error unless at least one of these is true of the active K8S context (i.e., what is returned by kubectl config current-context)
> 
> 1. The K8S API URL is on localhost.
> 2. The context name is one of a few known local context names (e.g,. “minikube”).
> 3. The context name is explicitly passed to allow_k8s_contexts in the Tiltfile.

(1) does not seem to be true. I'm running K3S on localhost and I get the "might be production" error. I looked up the source code and there's no check for localhost whatsoever, [tilt only checks for context names](https://github.com/windmilleng/tilt/blob/c1b0ddd07e65a207c7e26e65da0493f3e0fbb39d/internal/k8s/env.go#L35).

**Comment by landism** [comment]
It looks like the code changed after those docs were written. Sorry about that!

This quite possibly doesn't need saying, but, just in case, you can work around it in the meantime by calling `allow_k8s_contexts`.

**Comment by nicks** [comment]
it sounds like we should just update the documentation to reflect what the code actually does

**Comment by jgillich** [comment]
Thank you!
