### ISSUE TITLE
Using tilt with readOnlyRootFilesystem == true

### ISSUE THREAD

**Issue by ivanstanev** [windmilleng/tilt#2593]
Is there a way for Tilt to ignore the `readOnlyRootFilesystem` parameter set in my PodSecurityContext? I'm using Tilt with Helm and my Deployment has the parameter set for added security in the Pod, but Tilt fails to load the image if that parameter is set, so I have to explicitly mark it as `false` before starting to develop locally.

**Comment by jazzdan** [comment]
Hi @ivanstanev, can you provide the error message that Tilt shows when it fails to load the image? Thanks!

**Comment by ivanstanev** [comment]
Hi @jazzdan this is the output from Tilt:

```sh
my-app┊ npm ERR! code EROFS
my-app┊ npm ERR! syscall open
my-app┊ npm ERR! path /srv/app/.npm/_cacache/tmp/b7e99325
my-app┊ npm ERR! errno -30
my-app┊ npm ERR! rofs EROFS: read-only file system, open '/srv/app/.npm/_cacache/tmp/b7e99325'
my-app┊ npm ERR! rofs Often virtualized file systems, or other file systems
my-app┊ npm ERR! rofs that don't support symlinks, give this error.
my-app┊ bin/start-tilt: exec: line 4: tsc-watch: not found
my-app┊ [K8s EVENT: Pod my-app-bc6689bfc-2tfvm (ns: my-app)] Back-off restarting failed container

**Comment by jazzdan** [comment]
Hey @ivanstanev, that looks to me like an error from `npm` in your container, not from Tilt loading an image. I think that whatever `npm` is doing needs to be modified to handle read-only filesystems.

Something you could do is use Helm to remove the `readOnlyRootFilesystem` setting from your deployment when Tilt deploys it in dev only, but to keep it in prod.

I'm going to close this issue for now but please re-open if I misunderstood something!
