### ISSUE TITLE
Panic when expanding log interface in terminal.

### ISSUE THREAD

**Issue by virta-jasonmay** [windmilleng/tilt#2599]
```
docker_pa_frontend_1 exited with code 137
panic: runtime error: invalid memory address or nil pointer dereference
 ✓ OK                                                                                                                   panic: runtime error: invalid memory address or nil pointer dereference
```

This happens when I hit `x` the second time to have the logs fill the terminal pane. The whole tilt process crashes and sends me back to my shell prompt.

Here is my `tilt doctor` output:
```
Tilt: v0.10.20, built 2019-11-15
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.39
- Builder: 2
---
Kubernetes
- Env: microk8s
- Context: microk8s
- Cluster Name: microk8s-cluster
- Namespace: default
- Container Runtime: containerd
- Version: v1.16.3
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
- User Mode: default
- Machine: [redacted]
- Repo: [redacted]
```

**Comment by nicks** [comment]
Thanks for the report! 

I'm having trouble reproducing this...is there any chance you could take a screenshot? That sometimes gives interesting info...

unfortunately, RTY doesn't play well with how Go does panics :(

**Comment by virta-jasonmay** [comment]
@nicks 

![image](https://user-images.githubusercontent.com/55505808/69588141-9e196280-0f9c-11ea-9c69-ef0367f080c9.png)

It's running `npm install` - it works fine when I change it to `npm install --silent`, so I'm using that as a workaround at the moment.

**Comment by nicks** [comment]
that's exactly what i needed, thanks!

**Comment by virta-jasonmay** [comment]
It crashed even with `--silent` but it also ran an `npm run build-assets` command afterwards so that might potentially also cause the issue. Both commands use advanced ANSI sequences.
