### ISSUE TITLE
On Windows, Tilt can't find Helm installation

### ISSUE THREAD

**Issue by hyu** [windmilleng/tilt#2633]
From Kubernetes > #tilt, [davidford writes](https://kubernetes.slack.com/archives/CESBL84MV/p1575546886384700):

> [Tilt complains] it can't find my helm installation but it's definitely in my path.

> I believe the bug was introduced in version [v0.10.23](https://github.com/windmilleng/tilt/releases/tag/v0.10.23) and likely to be the following commit: [#2606 - tiltfile: support helm 3 in addition to helm 2](https://github.com/windmilleng/tilt/commit/db669506c9d040a8ffa608dd152c75fed2646ac8). The previous version ([v0.10.22](https://github.com/windmilleng/tilt/releases/tag/v0.10.22)) did not suffer from the issue I mentioned originally.

This error occurred running Tilt with minikube using the default configuration on the alpha Windows client.

Also didn't work with these variants: 
> I tried with helm v2 and v3 in my path as helm.exe and I also tried having the following in my path too helm.exe, helm2.exe , helm3.exe

**Comment by david-martyn-ford** [comment]
This is the output I got when when running `tilt up`

```
Starting Tilt (v0.10.23, built 2019-12-04)…
Beginning Tiltfile execution
Successfully loaded Tiltfile (3.9985ms)
Traceback (most recent call last):
  D:\optimise\Optimise.Tracking.IngressHandler\Tiltfile:8:12: in <toplevel>
  <builtin>: in helm
Error: Unable to find Helm installation. Make sure `helm` is on your $PATH.
```

My `Titltfile` looks something like this:

```
allow_k8s_contexts('minikube-windows')

docker_build('davidford/service1', './cmd/service1')
docker_build('davidford/service2', './cmd/service2')

yaml = helm(
  './deployment/helm-charts/davidford',
  name='test',
  namespace='default',
  values=['./deployment/helm-charts/davidford/values.yaml'],
  set=[
    'service1.image=davidford/service1',
    'service2.image=davidford/service2',

    'aws.accessKey=' + os.environ['AWS_ACCESS_KEY_ID'],
    'aws.secretKey=' + os.environ['AWS_SECRET_ACCESS_KEY'],
  ],
)

k8s_yaml(yaml)
```
