### ISSUE TITLE
Allow explicit disabling of BuildKit

### ISSUE THREAD

**Issue by rpocase** [windmilleng/tilt#2710]
When your docker daemon has the experimental flag enabled, tilt will (usually helpfully!) automatically enable `DOCKER_BUILDKIT`. When using certain dockerd settings (e.g. insecure registries per moby/buildkit#606), this can cause `docker_build` failures. 

Tilt should provide an option to explicitly disable DOCKER_BUILDKIT (or opt-in, but that is a backwards incompatible change from a docs perspective).

**Comment by jazzdan** [comment]
Hey @rpocase, if you set `DOCKER_BUILDKIT=0` when you run Tilt (i.e. `DOCKER_BUILDKIT=0 tilt up`) then buildkit should be disabled.

Does that work for you?

**Comment by rpocase** [comment]
That seems to work! I think the only thing that needs to change then is an update to the [FAQ](https://docs.tilt.dev/faq.html#q-docker-buildkit-is-cool-how-do-i-use-it).
