### ISSUE TITLE
Source build failure leads to error that is hard to understand

### ISSUE THREAD

**Issue by hausdorff** [windmilleng/tilt#2718]
In the newest version of Tilt, when I have a compiler error (didn't use a variable, say), it leads to the error below. It took me many minutes before I happened to see there was a source error, and that this is not a problem that tilt itself is having.

```
ERROR: ImageBuild: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c go build ./cmd/whatever]: runc did not terminate sucessfully
got unexpected error during build/deploy: ImageBuild: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c go build ./cmd/whatever]: runc did not terminate sucessfully
```

**Comment by nicks** [comment]
oof, thanks for the report. The buildkit error messages keep getting more inscrutable. I wonder if we can clean them up a bit and/or adopt some buildx code. lemme dig in a bit.

**Comment by nicks** [comment]
actually, can you double-check that you're running tilt v0.10.25? I'm having trouble reproducing this, and it looks like this was fixed in https://github.com/windmilleng/tilt/pull/2538.

Alternatively, is it possible to post a snapshot of the error?

**Comment by hausdorff** [comment]
Sorry, by "newest version of Tilt" I meant "newest version of Tilt _in Homebrew_", but as `tilt version` reports `v0.10.17, built 2019-11-01`, this evidently cannot have been true, even though I seem to recall running `brew upgrade tilt`.

In any event, after upgrading to `v0.10.26` this issue seems to have gone away, so I'll just close out and apologize for the sloppy bug report which should have included a version to begin with.
