### ISSUE TITLE
Add support for docker build --ssh in docker_build command

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#2736]
Requested in the #tilt channel, and separately in this issue request: https://github.com/windmilleng/tilt/issues/2437

I suspect it's straightforward, will add it now

**Comment by andymartin-sch** [comment]
may be closed by https://github.com/windmilleng/tilt/commit/e1f020ef163398d56fba5dc65da12450697bb868

**Comment by nicks** [comment]
oops! yes. i tagged the wrong issue. fixed in https://github.com/windmilleng/tilt/pull/2750
