### ISSUE TITLE
add build caching to reduce startup time

### ISSUE THREAD

**Issue by brechtvalcke** [windmilleng/tilt#2753]
Starting up 10+ services takes forever! Would be great to implement a caching system like skaffold to reduce startup times.

**Comment by nicks** [comment]
Hmmmm...everything should already be cached?

When I start up Tilt, all the docker builds should be cached and it will attach to the running pods.

Can you be more specific? Would it be possible to point to a particular repo, and what part of starting it feels slow to you?

**Comment by brechtvalcke** [comment]
Ok so turns out I just needed to restart my docker for mac kubernetes and it is caching now. However it still is kinda slow if you have a lot of services. 

I have only configured the 2 smallest services we have to test tilt out. This is the log of one of them:

```
Building with BuildOrder: BuildOrder{ *engine.LiveUpdateBuildAndDeployer *engine.DockerComposeBuildAndDeployer *engine.ImageBuildAndDeployer *engine.LocalTargetBuildAndDeployer }
Trying to build and deploy with *engine.LiveUpdateBuildAndDeployer
falling back to next update method because: In-place build does not support initial deploy
Trying to build and deploy with *engine.DockerComposeBuildAndDeployer
falling back to next update method because: DockerComposeBuildAndDeployer requires exactly one dcTarget (got 0)
Trying to build and deploy with *engine.ImageBuildAndDeployer
STEP 1/3 — Building Dockerfile: [bothive/dashboard]
Building Dockerfile:
  FROM node:10.14.2
  
  ENV PATH node_modules/.bin:$PATH
  COPY . .
  RUN rm -rf package-lock.json
  RUN rm -rf node_modules
  RUN npm i
  EXPOSE 3000
  
  CMD ["npm", "run", "start:tilt"]
  


  │ Tarring context…
  │ Building image
    ╎ copy /context /
    ╎ copy /context / done | 22.269s
    ╎ [1/5] FROM docker.io/library/node:10.14.2
    ╎ [cached] [2/5] COPY . .
    ╎ [cached] [3/5] RUN rm -rf package-lock.json
    ╎ [cached] [4/5] RUN rm -rf node_modules
    ╎ [cached] [5/5] RUN npm i
    ╎ exporting to image
    ╎ exporting to image done | 429ms

STEP 2/3 — Pushing bothive/dashboard:tilt-284ca99fcca6c929
    ╎ Skipping push

STEP 3/3 — Deploying
  │ Injecting images into Kubernetes YAML
  │ Applying via kubectl:
  │    dashboard:deployment

  │ Step 1 - 119.709s
  │ Step 2 - 0.000s
  │ Step 3 - 1.970s
  │ Done in: 121.679s 

```
What I notice is that tarring the context and copying it takes a long time in addition to the actual build.

And this is my tiltfile (very messy but just followed the node.js tutorial untill it worked):

```
k8s_yaml([
    'config/tilt/kubernetes/deployments/services/frontend/dashboard.yml',
    'config/tilt/kubernetes/deployments/services/frontend/intent-manager.yml',
])

update_settings(max_parallel_builds=2)

docker_build('bothive/dashboard', 'frontend/dashboard', dockerfile="frontend/dashboard/dockerfile-local", live_update=[
    fall_back_on(['frontend/dashboard/package.json', 'frontend/dashboard/package-lock.json']),
    sync('frontend/dashboard', '/'),
  ])
docker_build('bothive/intent-manager', 'frontend/intentManager', dockerfile="frontend/intentManager/dockerfile-local", live_update=[
    fall_back_on(['frontend/intentManager/package.json', 'frontend/intentManager/package-lock.json']),
    sync('frontend/intentManager', '/'),
  ])


k8s_resource('dashboard', port_forwards='3000')
k8s_resource('intent-manager', port_forwards='4000')
```
 I've seen you guys have merged some pull requests related to running parallel builds today. Can I use it already or is it not yet released?

**Comment by nicks** [comment]
ooh interesting. thanks for the context.

The parallel builds stuff should be in the next release. We're just doing a final QA pass on it.

The build context taking a long time to tar + send is interesting. Let me see do some research and maybe ask the Skaffold folks for their advice on this. I think all the toolmakers in this space (us + Skaffold + others) want the image build tooling to get a lot better, rather than everyone building their own caching logic. So I wonder if there's any movement towards a caching protocol that doesn't require the whole tarball.

As an aside, we've been talking about some tooling on how to alert you when docker for mac's kubernetes is slow and needs to be reset, which we think will apply to a lot of people.

**Comment by maiamcc** [comment]
Hey @brechtvalcke, have you gotten to try Tilt with the new [parallel update](https://blog.tilt.dev/2020/01/14/parallel-updates.html) functionality? Is it reducing your pain at all? Note that we set the default to 3 simultaneous updates, but you can pump it up as far as you want (until it fries your CPU).

**Comment by brechtvalcke** [comment]
Hi,

Yes I tried and it worked fine. 7 concurrent builds are possible on our
machine's and it doesn't fry our CPU :p.

Thank you for the quick implementation!

Met vriendelijke groeten
*Brecht Valcke*
Co-founder
Tel: +32 498 81 85 87 <+32498818587>
Email: brecht@bothive.be
[image: Bothive logo] <https://www.bothive.be/>
[image: like us on Facebook] <https://www.facebook.com/bothivechatbots> [image:
Visit our Linked in] <https://www.linkedin.com/company/14017546> [image:
Follow us on twitter] <https://twitter.com/bothive2> [image: Visit our
Instagram] <https://www.instagram.com/bot.hive>Snelle vraag over chatbots
of Bothive? Vraag het aan onze chatbot op de website
<http://www.bothive.be/> of Facebook Messenger <http://m.me/bothivechatbots>.
Zij staat 24/7 paraat om je onmiddellijk te helpen.


Op di 25 feb. 2020 om 00:19 schreef Maia McCormick <notifications@github.com

**Comment by maiamcc** [comment]
graag gedaan, en veel succes :)
