### ISSUE TITLE
Docs should clarify if tilt support two way file sync

### ISSUE THREAD

**Issue by ostrolucky** [windmilleng/tilt#2756]
Sometimes project generate cache during runtime that needs to be accessed via tools like IDE. I'm considering Tilt and need to know if it can be configured so it synces changes in container back to host.

**Comment by nicks** [comment]
Currently, we see most people set this up with a local_resource job that generates the cache on disk, and then a docker_build job that kicks off a build when that cache is generated. You can read an overview of this approach here:

https://docs.tilt.dev/local_resource.html

If you tell us more about the specifics of what you're doing, we can give you advice on how to set it up (the details are slightly different for yarn lock files vs go caches vs ruby gem lockfiles, etc)

We've worked with a couple of teams that have tried to build two-way file sync systems. We generally don't recommend it. They seem to always find that it's hard to set up, to debug problems. and to figure out what's going on. There are usually more robust ways to accomplish the same goal. (for past discussion on this, see https://github.com/windmilleng/tilt/issues/1956 and https://github.com/windmilleng/tilt/issues/1688)

**Comment by ostrolucky** [comment]
It's mostly about symfony cache, which is regenerated after each change in routing, config or DI services. It's important so IDE can follow these files during debugging.

**Comment by jazzdan** [comment]
@ostrolucky do you want to take the cache that is generated in the container and copy it down locally?

**Comment by ostrolucky** [comment]
Yep, exactly

**Comment by jazzdan** [comment]
I'm going to fold this issue in to #1956, but this is a really interesting use case that's unique to dev. Thank you for raising it!
