### ISSUE TITLE
Liveupdate 'run' before 'sync'

### ISSUE THREAD

**Issue by devcsrj** [windmilleng/tilt#2765]
According to the liveupdate ['run' section](https://docs.tilt.dev/live_update_reference.html#runcmd-str-triggernone-str--liststr):

> Currently, all of your run steps must come after all of your sync steps. (If you need different behavior, let us know!)

So here is my case, to let you know! 👂🏻

I have a gradle project, which uses [a plugin](https://bmuschko.github.io/gradle-docker-plugin/#spring-boot-plugin-extension) to build a docker image. Basically, it has 2 tasks that I can integrate with `Tilt`:

* `dockerBuildImage`
* `dockerSyncBuildContext` 

This means I can configure it such that, I can essentially do:

```python
custom_build(
    "ref",
    "./gradlew dockerBuildImage -PdockerRef=$EXPECTED_REF",
    ...
```

This works perfectly. 👍 

Now, the next part is to tell `Tilt` how to reload the app. If using **`run` before `sync` was allowed**, it can be achieved with:

```python
    live_updates=[
        run("./gradlew dockerSyncBuildContext")
        sync("./build/docker", "/app")
        restart_container()
    ]
```

The `./build/docker` directory generated by the plugin looks like this:

```
├── docker
│   ├── classes
│   ├── libs
│   └── resources
```

And the `Dockerfile` generated is pretty-straightforward:

```
WORKDIR /app
COPY libs libs/
COPY resources resources/
COPY classes classes/
```

But because `Tilt` doesn't allow **`run` before `sync`**, I cannot take advantage of this fact.

**Comment by nicks** [comment]
Thanks for the detailed report! That gradle plugin looks cool and something I want to play around with more.

It sounds like what you want is for `run("./gradlew dockerSyncBuildContext")` to execute locally, and then sync the generated files into the running pod. Is that right?

A `live_update=[run(...)]` runs inside the docker container, so isn't quite what you want. 

The way we typically see teams set this up is that they have a `local_resource` that compiles the build artifacts outside the container (see: https://docs.tilt.dev/local_resource.html), and then a live_update that watches the artifact directory and syncs them. Does that make sense?

**Comment by devcsrj** [comment]
> ...to execute locally, and then sync the generated files into the running pod

Yes, exactly.

> The way we typically see teams set this up is that they have a local_resource that compiles the build artifacts outside the container...

Oh, I'll check this out. I'll be back with an update!

**Comment by devcsrj** [comment]
Hi @nicks !

I got what I hoped to achieve, using the `local_resource` you described:

```python
custom_build(
    "app",
    "./gradlew dockerBuildImage -PdockerRef=$EXPECTED_REF",
    deps = [
        "./build/docker"
    ],
    live_update=[
      sync("./build/docker", "/app"),
      restart_container()
    ]
)

local_resource("app-sources"
    cmd = "./gradlew dockerSyncBuildContext",
    deps = [
        "./src",
        "./build.gradle"
    ]
)
```

Although I might need to find a way to optimize this further, as apparently the `dockerSyncBuildContext` is a bit slow (re-generates the entire `build/docker` dir), and causes Tilt to re-sync  **the entire** directory (for sure, due to timestamp changes).

Thanks for pointing me to the right direction!

**Comment by devcsrj** [comment]
So far, syncing only `/classes` and `/resources` seem to work best:

```python
context_dir = "./build/docker"
custom_build(
    "app",
    "./gradlew dockerBuildImage -PdockerRef=$EXPECTED_REF",
    deps = [
        context_dir + "/classes",
        context_dir + "/lib",
        context_dir + "/resources",
    ],
    live_update=[
        sync(context_dir + "/classes", "/app/classes"),
        sync(context_dir + "/resources", "/app/resources"),
        restart_container()
    ]
)

local_resource("app-sources"
    cmd = "./gradlew dockerSyncBuildContext",
    deps = [
        "./src",
        "./build.gradle"
    ]
)
```

This way, changes in the `lib` are done with full rebuild instead. Not so bad, since deps don't change so often anyway.
