### ISSUE TITLE
Should Tilt run live update run steps in WORKDIR?

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2786]
Currently if you have a Dockerfile that looks like this:

```Dockerfile
FROM alpine
WORKDIR /foo
RUN touch /foo/bar
```

With this Tiltfile:
```python
docker_build("foo, "."
  live_update=[
    sync('.', '/')
    run('stat bar'),
  ]
)
```

The live update run step will fail because it's still running in `/` instead of in the `WORKDIR` specified in the Dockerfile.

I think it would make more sense if live_update steps respected the `WORKDIR` in the Dockerfile but I'm willing to be convinced otherwise.

At the very least I think we should document this because I think it's confusing.

**Comment by nicks** [comment]
at the very least, it seems like you should be able to set the working directory of a `run` command manually, eg, `run('command', cwd=...)`, like in any other process execution api

**Comment by jazzdan** [comment]
Actually it does do this, so I'm going to close this issue. I feel like the fact that I was confused about this though means that we should do a better job of surfacing where run steps are being executed.
