### ISSUE TITLE
`tilt down` should work with Tiltfile Config (aka flags/args)

### ISSUE THREAD

**Issue by hyu** [windmilleng/tilt#2820]
From feedback from [@tmc in #tilt](https://kubernetes.slack.com/archives/CESBL84MV/p1579732637033600?thread_ts=1579707345.028400&cid=CESBL84MV).

If you run `tilt up [arg]` to run a subset of your app's services, there isn't a corresponding `tilt down [arg]`. The command is not recognized.

If you go ahead and run `tilt down`, it has no awareness if the last command was `tilt up [arg]` and proceeds to tear down all services as usual, which may have unintended consequences.

**Comment by maiamcc** [comment]
What exactly is happening? Repro steps?

**Comment by landism** [comment]
The first bit should be a few-line change in the command definition [here](https://github.com/windmilleng/tilt/blob/5475e98bd9f23d43f8495f04fbd6e473af3fd388/internal/cli/down.go#L25).

The last bit might be a tricky product question.

**Comment by landism** [comment]
#2848 addresses "tilt down doesn't work with args"

There's still no awareness of what the last tilt up was, so, e.g.:
```
tilt up a # start a
tilt up b c # start b and c
tilt down # stop everything (a, b, c)
```

There's also still a slightly thorny question about "uncategorized" yaml - for both `tilt up` and `tilt down` with args, we apply the command to the resources specified on the command line *and also all uncategorized yaml*, which is quite possibly not what the user wants (e.g., if you start services foo and bar in a namespace, the namespace will be uncategorized, and then `tilt down foo` will delete the namespace, even though bar still using it!)

I suspect the answer to that is a more complicated issue of providing users with a way to categorize all yaml, and worth considering separately.
