### ISSUE TITLE
Add support for multiple tags in a given docker_build command

### ISSUE THREAD

**Issue by andymartin-sch** [windmilleng/tilt#2839]
In the context of using Tilt in CI environments (#988), it would be nice if there were a way to have `docker_build` apply multiple tags to the images it produces (similar to how you can pass multiple `-t`s into a docker build execution).

For example, we currently have a jenkins build that runs `tilt up`. Once everything is built and the services are running, we have to manually re-tag the images Tilt produced with tags of `latest` and the jenkins build number before pushing the images to GCR.

The problems with this are:
1. it requires us to add more logic to our jenkins build steps.
2. if we ever stop running `docker system prune` at the start of our jenkins runs, the images from past builds may persist and we would then have to look at things like build timestamps to disambiguate which image was from the current `tilt up` run.

There are a few ways this could be implemented, but to get a conversation started, what if `docker_build` was extended to support an `extra_tags` argument that took a list of tags (strings)?

**Comment by nicks** [comment]
This makes sense to me. The flow I'm imagining (based on past experience with jenkins) is something like:

1) The jenkins job runs with the jenkins build ID as an env variable.
2) You have some Tiltfile code like:

```
extra_tags = []
jenkins_tag = os.environ.get('JENKINS_BUILD', '')
if jenkins_tag:
  extra_tags.append(jenkins_tag)
docker_build(..., extra_tags=extra_tags)
```

3) The jenkins job pushes the tagged image to GCR when Tilt finishes (i.e., Tilt isn't pushing the images at those extra tags)

Is that right?

**Comment by andymartin-sch** [comment]
Yep that's it.

This is probably an inconsequential extra detail, but in practice, we prefer to have each build tag the images it produces with (a) a tag name derived from the Jenkins build number as well as (b) a tag name that's just "latest".

**Comment by rpocase** [comment]
Just echoing my use case from #2880 since this should meet my needs as well.

> I have an eventual use case where I want to pass the docker_build image ID to other tooling (in my case, argo workflows) from within tilt. Technically, I could do this using k8s_yaml, but I may want to start a workflow on demand or even stop the workflow midway through.
> 
> I expect this could be done using use custom_build(..., tag=mytag), but that is cumbersome for just wanting to retrieve one attribute of the build.

I'm not immediately blocked on this at the moment as the current process is sufficient, but this being available may give me the nudge to rewrite the process as a Workflow.

**Comment by nicks** [comment]
v0.12.1 should now have an extra_tag argument for this
