### ISSUE TITLE
Force rebuilding in the cli

### ISSUE THREAD

**Issue by rmb938** [windmilleng/tilt#2894]
In the web ui there is a nice button to force a rebuild, however I can't find a way to do that in the cli.

Can this feature be added to the cli?

**Comment by maiamcc** [comment]
Hi @rmb938! Unfortunately, we're not adding new features to the CLI at this time, so this probably won't happen any time soon.

I'm curious why you'd prefer the CI to the web UI for running a force rebuild, though--can you elaborate a bit on how you use or don't use the two interfaces?

**Comment by maiamcc** [comment]
Hi @rmb938! Potentially--can you tell me more about your use case, and why you want to force a rebuild from the CLI instead of from the web UI?

**Comment by rmb938** [comment]
My workflows tend to be all done via a terminal and an IDE for development. Typically my web browser is never used other than looking at documentation and whatnot. I tend to mostly work on backend applications that have no http endspoints or just a basic api so my browser is never used for interacting with those applications.

Before starting to use tilt I typically ran kubectl and docker commands directly in my terminal. When using tilt I also use the terminal interface via `tilt up --no-browser`. Navigating the CLI interface is much easier for my work flows and being able to switch between all the different log types and whatnot is great.

All the features I currently use are already present in the CLI except the force rebuild button, so having to open the web ui just for that one feature is really annoying.

**Comment by maiamcc** [comment]
This is [live in v0.12.0](https://github.com/windmilleng/tilt/releases/tag/v0.12.0)! Syntax is `tilt trigger [resource_name]`:

![2020-02-07 13 52 58](https://user-images.githubusercontent.com/6332648/74057116-3bd3d980-49b1-11ea-9021-b20f2e6ee40f.gif)

**Comment by rmb938** [comment]
Thanks! I was hoping for more of a keybind, like the `X` key to expend the logs. But this works too.

**Comment by maiamcc** [comment]
Ah, I see. If you feel like submitting a PR, it should be pretty easy: [here's the code to trigger an update](https://github.com/windmilleng/tilt/blob/455f644554aabe6c5ec84b9fe2a2f8c13269ba46/internal/cli/trigger.go#L33), and [here's the code that handles terminal key events](https://github.com/windmilleng/tilt/blob/1521aeac180e5eea664a09773220c6963be5c06d/internal/hud/hud.go#L154). If you end up writing this yourself, let me know if you need any help.

**Comment by rmb938** [comment]
Awesome, I'll take a look. Thanks again!

**Comment by nicks** [comment]
i filed the TUI request as https://github.com/windmilleng/tilt/issues/2995, since jason may also asked about this
