### ISSUE TITLE
environment variables as build_args values

### ISSUE THREAD

**Issue by buhkguj** [windmilleng/tilt#2906]
I am tring to use my personal token inside the Dokerfile. But the environment variable does not expand. Is there a way?

Tiltfile:
` build_args={"TOKEN": "$GITLAB_TOKEN"},`

Dockerfile:
`ARG TOKEN`
`RUN env`

...
TOKEN=$GITLAB_TOKEN
...

**Comment by nicks** [comment]
The tiltfile has a os.environ dict
https://docs.tilt.dev/api.html#modules.os.environ

so this would look like:
build_args={"TOKEN": os.environ.get("GITLAB_TOKEN", "")}

does that work?

**Comment by buhkguj** [comment]
Thats working fine.
Thank you!
