### ISSUE TITLE
docker_build entrypoint removes args from Kubernetes deployment

### ISSUE THREAD

**Issue by vincepri** [windmilleng/tilt#2918]
This issue was originally reported in the Kubernetes [slack](https://kubernetes.slack.com/archives/CESBL84MV/p1581099402298600). 

It seems that the `docker_build` `entrypoint` argument, when set, wipes out both a Kubernetes Deployment command and args. We have a use case where the arguments are generated dynamically with `kustomize` and we need to preserve the args in our deployments to enable/disable some behaviors.

@maiamcc pointed out to https://github.com/windmilleng/tilt/blob/5d5545054425dfb4f00e8f9a61bd039680062904/internal/k8s/image.go#L215

It'd be great to either have a flag to disable wiping out the arguments, or fix the issue in some other way.

**Comment by maiamcc** [comment]
Thanks for filing @vincepri -- let me know how blocked you are on this, and we'll see how much work it is on our end and prioritize accordingly.

(Another possible stop-gap: if your args are dynamically generated by helm, why not dynamically generate the command as well, rather than using the `docker_build.entrypoint` param?)

**Comment by nicks** [comment]
I found this Kubernetes documentation helpful w/r/t thinking about this:

https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes

> If you do not supply command or args for a Container, the defaults defined in the Docker image are used.

> If you supply a command but no args for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored.

> If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.

> If you supply a command and args, the default Entrypoint and the default Cmd defined in the Docker image are ignored. Your command is run with your args.

The decision tree is already pretty complex. The addition of Tiltfile entrypoint adds some new branches to the decision tree:

> If you do not supply command or args in the YAML, but have a Tiltfile entrypoint override
> If you supply only a command in the YAML, but have a Tiltfile entrypoint override
> If you supply only args in the YAML, but have a Tiltfile entrypoint override
> If you supply a command and args in the YAML, but have a Tiltfile entrypoint override

I think I agree that the behavior most consistent with current Kubernetes behavior is that the Tiltfile entrypoint should always override command but never override args. 

Though in general I kind of want a visualizer for how these all compose together :joy:

**Comment by vincepri** [comment]
Hey folks, sorry for not following up sooner. We're not 100% blocked on this, we do have a workaround, but that loses the dynamic reload, which isn't great.

@maiamcc The commands are generated by `kustomize` for us depending on the folder they're in. When we apply the yaml in Tilt it comes as a blob that we don't know anything about.

**Comment by nicks** [comment]
this should be fixed in v0.12.1!
