### ISSUE TITLE
End-user release notes

### ISSUE THREAD

**Issue by rpocase** [windmilleng/tilt#2940]
When I see a new tilt release, I first try to comb through the release notes to see if I'm interested in any of the new items. The commit tags tend to be fairly helpful in discerning what I might care about, but I still have to unravel the trail. It would be nice to have a quick blurb for items that an end-user really care about (perhaps in addition to a commit log at the end).

**Comment by nicks** [comment]
Thanks for the report!

We've talked a bit about this. My general sense are that different users are looking for very different things from the release notes. Tilt "end-users" cover a wide range, e.g.:

- people who don't care about Kubernetes internals at all and just want to develop their app
- people like the ClusterAPI contributors who care a lot about the exact way that Tilt interops with different types of Kube clusters
- devtools admins who want to know if the latest version of Tilt is safe to rollout to their team

One possibility is that we'll have some sort of "release channel" system you can subscribe to, with recommendations on whether Tilt release X is important for you.

**Comment by nicks** [comment]
We've playing around with a brief release notes section at the top of the release description. Thanks @victorwuky !

Here's an example: https://github.com/windmilleng/tilt/releases/tag/v0.13.1

And also a product direction roadmap: https://tilt.dev/product_direction
