### ISSUE TITLE
Dockerfile image ref injection between dependent images fails if tag is a build arg

### ISSUE THREAD

**Issue by elemental-lf** [windmilleng/tilt#2943]
Image reference injection into a child's `Dockerfile` fails if the tag is a reference to a build argument. The injection works as expected when the tag is missing or is simply a string. 

It also fails if the whole image reference is a build argument (`FROM ${IMAGE_REF}`) even when the build argument references the parent image. But I suspect this might be harder the fix than the first use case.

I tried to work around this limitation by using `custom_build()` and `$EXPECTED_REF` and this works to some degree but fails in the end because there is no way to express the dependency between the two images and so the parent image might not exist when the custom build is started.

This is with version `0.12.1`.

### Tiltfile

```python
docker_build(
    'parent',
    'parent',
    dockerfile='Dockerfile.parent',
)
docker_build(
    'child',
    'child',
    dockerfile='Dockerfile.child',
)
```

### Dockerfile.parent

```dockerfile
FROM scratch
```

### Dockerfile.child
```dockerfile
ARG TAG="latest"
# This reference is not replaced as expected.
FROM parent:${TAG}
```

**Comment by elemental-lf** [comment]
For my unsuccessful `custom_build()` workaround there is some related discussion in https://github.com/windmilleng/tilt/issues/2856 as I've just noticed.

**Comment by nicks** [comment]
Is it possible to rewrite Dockerfile.child to use a FROM with a literal image reference?

Ya, there's a couple of different ways you could approach this:
- Make docker_build smarter about injecting into Dockerfiles with build args
- Make custom_build extensible enough that it can depend on other image builds

It might help to have a little bit more context on what you're trying to do. Is the real dockerfile you're using exactly `FROM parent:${TAG}`, and would making it smart enough to handle that pattern be good enough? Or would it need to be a little smarter?

**Comment by elemental-lf** [comment]
> It might help to have a little bit more context on what you're trying to do. Is the real dockerfile you're using exactly `FROM parent:${TAG}`, and would making it smart enough to handle that pattern be good enough? Or would it need to be a little smarter?

Thank you for the quick response! The use case is actually similar to the one Tilt has. The build pipeline of the project in question builds multiple versions of a set of dependent images. All images belonging to one version have the same tag. To ensure that a child image is based on the correct parent image the build process injects the tag of the parent image to use as a build argument. So as far as I can see support for `FROM parent:${TAG}` would be sufficient to use Tilt together with these `Dockerfile`s.

**Comment by nicks** [comment]
Thanks, makes sense to me! Let me poke at it later this afternoon just to get an estimate for how hard it would be to do this.

**Comment by nicks** [comment]
the fix should be in the next release!
