### ISSUE TITLE
Secrets not grouped with the rest of the resources

### ISSUE THREAD

**Issue by justin1121** [windmilleng/tilt#2951]
When compiling a helm chart into a single yaml file and running it with `k8s_yaml` a secret included in the final yaml file isn't being grouped together with the rest of the resources. Is this on purpose? How can I get the secret to be grouped with the rest of the resources in the UI?

Thanks!!

**Comment by nicks** [comment]
Good question! Tilt organizes things by workloads (objects with containers/images), since these tend to be things with logs and with long build steps. For more info, see:
https://docs.tilt.dev/tiltfile_concepts.html#resources

You can also use `k8s_resource` to create your own resource grouping.

Can you be a little bit more specific about what grouping you're expecting and why? Usually we see secrets deployed first with the 'uncategorized' bucket, so that the're available as other resources come up

**Comment by justin1121** [comment]
We've been deploying postgres from a chart (https://github.com/helm/charts) inside of our local development environment using tilt. We create the postgres resource by downloading the chart and feeding it through `k8s_yaml(helm())` We added a resource that doesn't automatically run so that we can quickly delete database if it gets corrupted. This includes deleting the uncategorized secret and the rest of the resources. When we go to bring back the database we can click on the postgres resource in the UI to bring back everything but the secret. We'd have click on the uncategorized resource to bring back the secret as well. We're just trying to make this flow as simple as possible. Two solutions I see:

- Require the developer to have to click "delete db" -> "postgres resource" -> "uncategorized".
- Put the secret in separately so that its not deleted when we delete the database. (This is probably the best was just hoping there would be an even better solution/I'm missing something obvious.

I've included parts of our `Tiltfile` deploy.

```
fetch_script = "helm fetch stable/postgresql --untar --untardir ./deploy/helm/"
local(fetch_script + " || true")
pg_yaml = helm('deploy/helm/postgresql', name=db_name,  set=['postgresqlPassword=' + db_pw], values=['./deploy/helm/postgresql/values.yaml'])
k8s_yaml(pg_yaml)
k8s_resource(db_name + '-postgresql', port_forwards=5432)

# Deleting the helm chart doesn't delete the PVC that the helm chart creates
# So, we explicitly delete it here with kubectl
delete_db_chart = 'echo "' + str(pg_yaml) + '" | kubectl delete -f -'
delete_pvc = 'kubectl delete pvc/data-' + db_name + '-postgresql-0'
delete_cmd = ' && '.join([delete_db_chart, delete_pvc])

local_resource('delete db', cmd=delete_cmd, trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False)
```

**Comment by nicks** [comment]
ya, this seems like a reasonable way to set things up. 

Try adding this snippet to your Tiltfile:

```

db_resources = [decode_yaml(yaml) for yaml in str(pg_yaml).split('\n---\n')]
without_secret = [r for r in db_resources if r["kind"] != 'Secret']
delete_db_chart = 'kubectl delete ' + ' '.join([(r["kind"] + "/" + r["metadata"]["name"]) for r in without_secret])
```

that way, you don't delete the secret when you click 'delete db'. This could be a lot easier to do :\

**Comment by justin1121** [comment]
Genius! That works, thanks!
