### ISSUE TITLE
build reasons render incorrectly in snapshots

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#2967]
In web ui:
![image](https://user-images.githubusercontent.com/7453991/74666719-0036cd80-5170-11ea-89b9-06737ce77afc.png)

In snapshot:
![image](https://user-images.githubusercontent.com/7453991/74666737-075ddb80-5170-11ea-86e6-b00444b1a08d.png)

**Comment by nicks** [comment]
can you link to the snapshot?

**Comment by landism** [comment]
https://cloud.tilt.dev/snapshot/AcbC1eQL1Nb-MvOKnfE=
