### ISSUE TITLE
Where no kubernetes resources are used, the kubeconfig should not be checked

### ISSUE THREAD

**Issue by theothertomelliott** [windmilleng/tilt#3021]
We have a few use cases where `tilt up` will have local resources, and docker compose resources, but nothing in Kubernetes.

When a user has an invalid kube context, this can prevent Tilt from starting at all (in the case I saw, a pre-existing minikube context after uninstalling minikube errored out because of a command run to find the minikube ip).

It would be great if this check was skipped when Kubernetes was not required to run a particular Tiltfile, to make it easier to get people up and running with simple use cases.

**Comment by jazzdan** [comment]
Somewhat related to https://github.com/windmilleng/tilt/pull/2595/files

**Comment by jazzdan** [comment]
Hmm @theothertomelliott I can't reproduce this.

Here's what I did:

1. `mv ~/.kube ~/kube.bak`
2. `git clone github.com/windmilleng/servantes`
3. `tilt up --file Tiltfile.dc`

Can you paste the exact error message you're getting, along with the results of `tilt doctor`?

**Comment by nicks** [comment]
I can reproduce this! It's very particular to minikube, which has a very different init codepath than other cluster types. You basically need to uninstall minikube, but have a valid minikube config, and you'll get:

```
$ tilt up --hud=false
Starting Tilt (v0.12.4-dev, built 2020-02-26)…
Error: Could not read node IP from minikube: exec: "minikube": executable file not found in $PATH
```

**Comment by jazzdan** [comment]
Oh sweet. Is that what you're seeing @theothertomelliott?

**Comment by theothertomelliott** [comment]
That's exactly the error! Thanks @nicks :)
