### ISSUE TITLE
possible documentation error in live_update_reference.html

### ISSUE THREAD

**Issue by bkcsfi** [windmilleng/tilt#3037]
on this page https://docs.tilt.dev/live_update_reference.html, is the following text:

_If you have multiple Docker images that depend on each other, you can sync files from anywhere within the contexts of any of the images. (In the diagram above, Tilt is building two images; the red image depends on–i.e. FROM’s–the yellow image.)_

However the red image is named `base_image` and it's stored in a folder named `common`

it seems like perhaps the yellow image should depend on the red image, which is opposite to what the text says.

**Comment by nicks** [comment]
thanks! Agreed, this is a mistake, I'll fix it now
