### ISSUE TITLE
Coloring logs are not working with tilt (Node.js ~ pino)

### ISSUE THREAD

**Issue by Tchoupinax** [windmilleng/tilt#3038]
Hello,

I see my logs are not colored while it is outside of tilt (launching node process on my  host).

Trace of the question posted on the slack:

> Hello,
I would like to know how can i add color to my logs in tilt ?
I see that postgres container or gitea container show colored logs, but with my Node.js service (using https://github.com/pinojs/pino) all logs are white. Should i implement special logs ?
Thank you :slightly_smiling_face:

It works with Gitea
![image](https://user-images.githubusercontent.com/9136206/75621392-feb7cd00-5b93-11ea-9a12-a153ada1ac10.png)

but not with my service
![image](https://user-images.githubusercontent.com/9136206/75621401-10997000-5b94-11ea-8a7e-32300941cb27.png)

@nicks made an example with pino and its example works (i tried it)

> Hmmm...it seems to work OK for me when I tried it: https://cloud.tilt.dev/snapshot/AbTt1-UL4p2zkcdvpNs=

> Here's a quick demo branch (https://github.com/windmilleng/nodejs-express-k8s/tree/nicks/pino). We want Tilt to be able to support colored logs, so if there's something that it's not doing right we want to fix it!

According to its example, i tried to add the pino-pretty pipe in the launch command (like `ENTRYPOINT node server.js | pino-pretty -c`) but it does not work for me.

How i declared pino : 

```javascript

const logger = pino({
  level: config.logger.level,
  prettyPrint: {
    levelFirst: true,
    translateTime: 'HH:MM:ss.l',
  },
});
```

my Dockerfile

```Dockerfile
FROM node:13 as nodeCustom

ENV APP_ROOT /app
ENV APP_PORT 8002

ENV LOGGER_LEVEL debug
ENV LOGGER_PRETTY true

RUN deluser --remove-home node && \
    groupadd user && \
    adduser --system --group user && \
    mkdir ${APP_ROOT} && chown -R user:user ${APP_ROOT}

WORKDIR ${APP_ROOT}

USER user

COPY --chown=user:user package*.json /app/

RUN npm install --production --no-progress && npx modclean -r

COPY --chown=user:user . .

EXPOSE ${APP_PORT}

CMD npm start
```

Thank you for your feedback :)

**Comment by nicks** [comment]
OK! I see the problem.

You need to change `pino` to

```
const logger = pino({
  level: config.logger.level,
  prettyPrint: {
    levelFirst: true,
    translateTime: 'HH:MM:ss.l',
    colorize: true,
  },
});
```

Here's what's happening: by default, `pino` auto-detects if your terminal supports color. When you run your app on Kubernetes, `pino` doesn't know if Kubernetes supports color or not, so it disables color. You can override it by explicitly specifying `colorize: true`, or using the environment variable `FORCE_COLOR=1`

For more, see:
https://github.com/pinojs/pino-pretty#options
https://www.npmjs.com/package/chalk#chalksupportscolor

**Comment by Tchoupinax** [comment]
Thank you a lot
