### ISSUE TITLE
Regression: live update always defaults to exec updater

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#3061]
The fix for #2948 cause a regression: a user in #tilt reported consistent "ExecUpdater does not support restart_container() step" errors even tho they expected tilt to use the Synclet.

#3050 is the cause: as a prerequisite to using the synclet, we check the last result for the k8s target to see if it has the `HasEligibleSynclet` flag. However, this didn't work in practice because, when we construct a buildEntry, [we don't add k8s results to the buildStateSet](https://github.com/windmilleng/tilt/blob/136f1624c77c8eb585c6660c89a2fedba992c0a1/internal/engine/buildcontroller.go#L191); no k8s result ever made it to the new code that checks the synclet eligibility flag.

The offending PR [has been reverted](https://github.com/windmilleng/tilt/pull/3055), but we should fix this behavior and re-apply the PR.

**Comment by nicks** [comment]
I'm going to close this ticket and re-open the other one, since this issue is fixed by https://github.com/windmilleng/tilt/pull/3055
