### ISSUE TITLE
Feature request: Enable additional resources at runtime

### ISSUE THREAD

**Issue by theothertomelliott** [windmilleng/tilt#3065]
We've got a root Tiltfile set up that allows a developer to specify one of hundreds of resources in our monorepo (with local_resource).

A few of our developers have requested the ability to enable additional resources in Tilt at runtime.

**Comment by maiamcc** [comment]
@theothertomelliott let me see if I'm understanding this right: as a dev, I can run `tilt up a b c` to run resources a, b, and c; but if I wanted to add resources d and e to the set of stuff I'm running, I currently have to quit tilt and run again with `tilt up a b c d e`, and I want a way to change the set of running resources without having to stop tilt and run again with different args. Is that right?

IF I'm understanding this correctly, then good news, [we already support this!](https://docs.tilt.dev/tiltfile_config.html#changing-args-at-runtime) If I'm misunderstanding, can you elaborate on your usecase?

**Comment by theothertomelliott** [comment]
Oh, I think I misunderstood that part of the docs! Let me have a play around and confirm.

**Comment by theothertomelliott** [comment]
Confirmed, that is exactly what I was talking about!

We'll need to make sure we document this for our particular set up. I think the `--to-edit` example threw me a little.
