### ISSUE TITLE
custom_build doesn't automatically ignore .git

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#3072]
According to [this doc](https://docs.tilt.dev/file_changes.html#git):
> Tilt will always ignore changes under the .git directory.
> 
> When you use docker_build() in your Tiltfile, Tilt will remove .git from the Docker context.

However, this isn't actually the case: we create a `.git` ignore pattern [for every directory we guess might be a "repo" for a given image](https://github.com/windmilleng/tilt/blob/0a968adb57c76a73a8c9bf5541c2d2a80bd3cefc/internal/tiltfile/docker.go#L503), but we have no logic in place to guess what might a "repo" for a custom build.

Possible solutions:
- treat every directory in `custom_build.deps` as a possible repo
- ignore `**/.git` always

**Comment by jazzdan** [comment]
Fixed as of https://github.com/windmilleng/tilt/commit/d7d61a7ec6697f0c44bbfea8aa7c7e9083092504
