### ISSUE TITLE
Error: ErrImageNeverPull on docker_build() command

### ISSUE THREAD

**Issue by nvowell** [windmilleng/tilt#3079]
I started getting this error in v0.12.6, and it's still happening in v0.12.8. I've downgraded to v0.12.5 for now, which fixed the issue for me.

```
[K8s EVENT: Pod podname-54d9fff45c-nrq7x (ns: default)] Container image "username/image:tilt-6275f731c7110a74" is not present with pull policy of Never
[K8s EVENT: Pod podname-54d9fff45c-nrq7x (ns: default)] Error: ErrImageNeverPull
```

I've tried messing with my yaml files, setting imagePullPolicy to Always, IfNotPresent, but doesn't fix the problem. It happens on every image built using the command docker_build(), everything else seems to work fine. My Tiltfile looks more or less identical to the example Tiltfile

```
k8s_yaml('app.yaml')

docker_build('companyname/frontend', 'frontend')
docker_build('companyname/backend', 'backend')
# ...

k8s_resource('frontend', port_forwards=8080)
```

Tilt: v0.12.6, built 2020-03-06
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 1
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.17.3
---

**Comment by nicks** [comment]
Oh no! That doesn't look right. Thank you for posting the `tilt doctor` output. it looks like Tilt isn't talking to the minikube docker-env properly.

Would it be possible to post the output of:

```
minikube docker-env
```

and also post the output of `tilt doctor` on Tilt v0.12.5?

**Comment by nvowell** [comment]
I read through the commits for v0.12.6, and I've identified the cause of the error. I'm running minikube, but not on my local machine, which seems to be causing the problems.

I tried using the custom_build() command instead of the docker_build(), and using the skips_local_docker=True, but this also does not fix the problem.

Is there any way to pass an alternate environment to Tilt so that it's not expecting the images on the local machine?

**Comment by nvowell** [comment]
Tilt: v0.12.5, built 2020-02-27
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: minikube-legion
- Cluster Name: minikube-legion
- Namespace: default
- Container Runtime: docker
- Version: v1.17.3
---


minikube docker-env output:
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/home/nick/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKER="minikube"
```

**Comment by nicks** [comment]
ya, I think you might be hitting the same issue as https://github.com/windmilleng/tilt/issues/2895

The current work-around is to change the cluster name in your kubeconfig to something else, so that Tilt does not assume it's a local minikube.

**Comment by nvowell** [comment]
Works great, thanks for quick response!!

**Comment by nicks** [comment]
Sorry for the trouble! We're experimenting with better solutions for this. Let me leave the issue open for now, until we can figure out how we're going to consolidate them / figure out a solution.

Background (for the person triaging this on Monday): Tilt tries hard to talk to the in-cluster minikube Docker daemon, which is much faster and safer because don't need to push/pull images and manage registry auth. But if it can't connect, it falls back to a "normal" push/pull image flow. The error message here means that parts of Tilt think it's in the first flow, and other parts of Tilt think it's in the second flow. It's a similar problem - but a much different failure case - than the other issues we've seen with minikube cluster detection.

**Comment by nicks** [comment]
on second thought, I just deleted my last comment and filed this as a separate issue: https://github.com/windmilleng/tilt/issues/3080 for more discussion. thanks again for reporting!
