### ISSUE TITLE
Tiltfile Path Manipulation Functions

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#3086]
There are lots of instances where you want to manipulate paths when writing a Tiltfile, especially in a many-repo situation and especially with `local_resource`.

We should expose the most useful functions of [`os.path`](https://docs.python.org/3/library/os.path.html).

**Comment by nicks** [comment]
Related issue: https://github.com/windmilleng/tilt/issues/2098 (just for os.path.realpath)
