### ISSUE TITLE
Use same colors from terminal log output in Tilt web logs

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3113]
The logs in Tilt web are all white on a dark green background. It is not easy to distinguish between different logical sections even with the spacing / indentation. 

Prior to a user running `tilt up` in their terminal, they are already running certain programs / services that they want to move into Tilt. Those might be outputting logs with certain colors and/or the terminal may have certain color configurations _already_. We should consider how to best take this color information and replicate it in the Tilt web ui to allow users to have a consistent experience. Especially for new users who may be doing development locally on their machines and have gotten used to a certain color scheme in their terminal, we want to retain that experience once they start in Tilt.

<img width="1662" alt="Screen Shot 2020-03-25 at 11 24 56 AM" src="https://user-images.githubusercontent.com/10860550/77553563-58f23800-6e8b-11ea-9f0b-ae466ac15fcc.png">

**Comment by nicks** [comment]
just as a note, that's a pretty old screenshot, and doesn't represent the current state of headers/color

**Comment by victorwuky** [comment]
Thanks @nicks . I replaced with an updated screenshot.

**Comment by jazzdan** [comment]
The dotnet compiler's colors come through, FWI: https://cloud.tilt.dev/snapshot/AYrj2-cL3CIknraEQ8c=

**Comment by landism** [comment]
IIUC:
* the original wording of this issue is worded along the lines of having tilt add new colors to logs that don't already have them, to make things clearer
* the report that led to this issue was about a case in which a program's logs had colors when run outside of Tilt, but when run inside of Tilt, none of the colors showed up.

I'm not aware of any users giving us feedback on the former, so I think it makes sense to reword this issue to the latter.

**Comment by victorwuky** [comment]
Thanks @landism for explaining further. That makes sense. I suggested something in the updated title and description. Feel free to update it directly if it needs to be further refined.

**Comment by nicks** [comment]
Is this equivalent to https://github.com/windmilleng/tilt/issues/3038 ?

Some apps auto-detect whether they should run with colors, and sometimes that auto-detection falls down. Tilt doesn't have much control over this, so usually the solution is to add some env varable or flag to force color.

Can we get a little bit more detail on the exact configuration the user is having issues with? Possibly a repro case?

**Comment by victorwuky** [comment]
Thanks @nicks . I believe it is indeed a duplicate. So I'll close this issue.

See this original internal thread from a user: https://windmill-eng.slack.com/archives/CTLBW1RA8/p1585145355016300?thread_ts=1585142242.015100&cid=CTLBW1RA8
