### ISSUE TITLE
Expose os.path.exists

### ISSUE THREAD

**Issue by rpocase** [windmilleng/tilt#3173]
I have a use case where I generate a file mid tilt run and use `read_file` to supply a value to `helm(..., set=[])`. If the file does not exist before running, tilt errors on the `read_file`. The final file content HAS to be generated during the tilt run as tilt manages resources that provide content to the file.

There are a couple approaches here, but a short term workaround looks like:

```python
local('local('if [ ! -e .generated ]; then touch .generated; fi')
```

It'd be nice to have a more idiomatic way to express the condition.

```
if not os.path.exists('.generated'):
   local('touch .generated')
```

Alternatives:
* ~An ensure_exists(file_path) could wrap the functionality, but is less general purpose~ (`read_file(...,default='')` is probably sufficient for most use cases where you would want this)
* A resource to express files that are generated during a tilt run to use as a dependency (seems harder, but I think there are probably a lot of good use cases here)

**Comment by rpocase** [comment]
@landism Pointed out that `read_file` takes an optional `default` argument, which would at least satisfy my initial use case. The first alternative likely has very little value in that case, but I could imagine uses for the latter where I'm not directly reading the file.

**Comment by victorwuky** [comment]
@rpocase : This is now available in the latest version of Tilt. https://docs.tilt.dev/upgrade.html
