### ISSUE TITLE
Command line filename option for Tiltfile

### ISSUE THREAD

**Issue by RKB-Quixote** [windmilleng/tilt#3180]
Would be useful to have a command

`Tilt --tiltfile=.tilt.star up`
`Tilt -f .tilt.star up`

Command line option to create Tiltfile that

1. Has star extension for use with VScode sysntax highligting
2. Can be used to hide tilt commands similar to a .drone.yml
3. Could allow alternative Tiltfiles in a single repo (optional)

An alternative for 1&2 would be to look for Tiltfile, then .tiltfile.star if command line option difficult for up and down commands.

Not sure if there is an option in the args command.
If so it's well hidden.

**Comment by nicks** [comment]
Is `tilt up --file` what you're looking for? Here's the cli reference docs that may help!

https://docs.tilt.dev/cli/tilt_up.html

**Comment by RKB-Quixote** [comment]
Now I'm embarrassed. Read the docs! 
Thank you.

**Comment by RKB-Quixote** [comment]
Thank you Nick.

Hopefully you all secure. NYC is going through hell.

Best wishes.
