### ISSUE TITLE
How to uninstall tilt?

### ISSUE THREAD

**Issue by javierdelgado1** [windmilleng/tilt#3184]
I think I have installed wrong tilt with sudo permissions, this is wrong and I need to delete it in ubuntu 19.10

**Comment by maiamcc** [comment]
@javierdelgado1 Tilt is just a binary, so all you have to do is delete that binary.

1. make sure the `tilt` in your path is the thing you intend to uninstall (sometimes people see collisions with a ruby gem of the same name). in your terminal, run `tilt help`; it should give you something like:
    ```
    Tilt helps you develop your microservices locally.
    Run 'tilt up' to start working on your services in a complete dev environment
    configured for your team.
    
    Tilt watches your files for edits, automatically builds your container images,
    ...
    ```

2. then you can just delete the binary:
    ```
    sudo rm $(which tilt)
    ```
    (generally the `sudo` isn't necessary, but if you said you needed su permissions to install it then i assume you need su permissions to delete it)

does that answer your question?

**Comment by khos2ow** [comment]
May be worth noting that another binary called `tilt` is also available and it's part of [ChefDK](https://downloads.chef.io/chefdk).
```
[:~] $ which tilt
/opt/chefdk/embedded/bin/tilt
```
and I had to create an alias
```
alias tiltd='/usr/local/bin/tilt'```

**Comment by maiamcc** [comment]
Going to go ahead and close this, but let us know if you're still having trouble!
