### ISSUE TITLE
cmd doesn't work for local_resource for Windows

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3189]
As mentioned in https://kubernetes.slack.com/archives/CESBL84MV/p1586346098114100:

"cmd runs commands starting "sh -c ..." and that's not working in Windows"

**Comment by nicks** [comment]
fixed by https://github.com/windmilleng/tilt/pull/3210

**Comment by victorwuky** [comment]
Thanks @nicks . I've informed the user in Slack, in that linked thread.
