### ISSUE TITLE
Error when using k8s_yaml( ) with a Job yaml

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3190]
The https://docs.tilt.dev/api.html#api.k8s_yaml function should work with a Kubernetes yaml file, including one of type Job, i.e. https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

But per this report in Slack #tilt, we are seeing an error: https://kubernetes.slack.com/archives/CESBL84MV/p1586364244120800

**Comment by maiamcc** [comment]
Closing in favor of #3196.
