### ISSUE TITLE
log output from initContainers is not shown in console or web UI - feature

### ISSUE THREAD

**Issue by bkcsfi** [windmilleng/tilt#3206]
I have a Pod with an initContainer. Logs from the Pod are shown in Tilt, but initContainer logs are not displayed. In my case the initContainer is restoring a database. Without the log output it appears the Pod is hung. I have to check it with k9s

Is it possible to show initContainer logs in tilt?

**Comment by victorwuky** [comment]
Thanks @bkcfsi:  We have this already logged in #2292. Do you mind 👍 that issue there? We have a few thumbs there already and hope to prioritize work at some point. 

I’ll close this one out so that we don’t have duplicates.
