### ISSUE TITLE
tilt image pruner is too aggressive

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#3211]
This is hard to repro in a self-contained way. The docker_prune_settings sets a minimum interval of 1 hour. This means that it's hard to deterministically hit this bug unless you have Tilt running for an hour (though there are ways to non-deterministically hit it)

Repro steps:
1) Modify the docker prune settings to interval = 
1 minute and max-age = 1 minute
https://github.com/windmilleng/tilt/blob/master/pkg/model/docker_prune.go#L6
2) Recompile tilt
3) Go to tilt.build and run `tilt up --debug --web-mode=prod tilt-site`
4) Wait a minute
5) Modify index.md to do a live update (which also makes the image pruner kick in)
6) Quit Tilt
7) Run `tilt up --debug --web-mode=prod tilt-site`

Expected result:
The old image should still be cached, because Tilt was just using it

Actual result:
The cache has been deleted, and Tilt has to rebuild everything from scratch

Other notes:
Discovered this while getting some odd reports from Jason May about Tilt mysteriously rebuilding things from scratch (where "from scratch" takes over an hour), but sometimes pulling images prematurely helped.

Ideally, docker_prune_settings() would have better options for reproing/debugging these kinds of problems, though that seems out of scope for this issue

**Comment by maiamcc** [comment]
does `tilt docker-prune` help with this debugging at all?

**Comment by nicks** [comment]
ya that would have helped if i had understood what the issue was before i started!
