### ISSUE TITLE
Add PriorityClass to the k8s entity ordering list

### ISSUE THREAD

**Issue by dominikdassow** [windmilleng/tilt#3240]
The ordering list in https://github.com/windmilleng/tilt/blob/master/internal/kustomize/ordering.go#L28 states that it's adapted from Kustomize but it's not in sync. They at least added PriorityClass (https://github.com/kubernetes-sigs/kustomize/commit/6c44da52a25cf2dfbb4ca9903e1da1e2f1df4bf0).

Noticed while searching for a solution to these errors:
`[K8s EVENT: ReplicaSet auth-db-79cd9d4d8c (ns: default)] Error creating: pods "auth-db-79cd9d4d8c-" is forbidden: no PriorityClass with name system was found`
Kubernetes handles the error and sets the correct PriorityClass to the pod afterwards but I'd like to get rid of the error message after `tilt up`.

**Comment by nicks** [comment]
thanks for the detailed report! adding it now

**Comment by victorwuky** [comment]
@dominikdassow : This is now fixed in the latest release. You can download here: https://docs.tilt.dev/upgrade.html.
