### ISSUE TITLE
Parameter docs for local are incorrect

### ISSUE THREAD

**Issue by jfancher** [windmilleng/tilt#3278]
The API docs for `local` suggest that the first parameter is named `cmd`:
https://docs.tilt.dev/api.html#api.local

However, it actually seems to be named `command`:
https://github.com/windmilleng/tilt/blob/master/internal/tiltfile/files.go#L28

I ran into this when I tried to invoke `local(cmd = "...")` with an explicit param name.

I'm not sure which is correct, but other data points:
 - `local_resource` and `run` use `cmd` (and docs and code seem to match)
 - `custom_build` uses `command` (and is documented as such)

**Comment by ellenkorbes** [comment]
Hey @jfancher, thanks for reporting this!

A fix is en route 😇

**Comment by maiamcc** [comment]
[Docs updated](https://docs.tilt.dev/api.html#api.local), good catch!
