### ISSUE TITLE
Improve node read permission error message, provide a way to disable

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#3280]
If you don't have permissions to read nodes when you start Tilt you'll get this error message:

```
Starting Tilt (v0.12.2, built 2020-02-21)…
ERROR: Tilt could not read your node configuration
 Ask your Kubernetes admin for access to run `kubectl get nodes`.
 Detail: nodes is forbidden: User "myuser" cannot list resource "nodes" in API group "" at the cluster scope
```
We should do more to explain what this error means and in what situations it's safe to ignore.

Additionally we provide a way to disable this check if a user decides they don't care about the optimizations it would enable.

**Comment by nicks** [comment]
I'd be in favor of just removing this message or making it a Debug log. The synclet is the only thing that needs the container runtime (https://github.com/windmilleng/tilt/issues/3245), and as we de-emphasize it, this will be much less important
