### ISSUE TITLE
Cannot sign in (via GitHub) in Tilt, when you already signed in to Tilt Cloud 

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3307]
See https://kubernetes.slack.com/archives/CESBL84MV/p1588944318467100

<img width="887" alt="Screen Shot 2020-05-08 at 9 39 48 AM" src="https://user-images.githubusercontent.com/10860550/81411112-e58d4880-910f-11ea-9921-298f5d9eb759.png">

**Comment by maiamcc** [comment]
FWIW I don't think this is a bug so much as misleading copy--if we took out the "sign in" link and made the big blue button say "Sign Up / Connect Your Account",  I think everything would work as people expected.

**Comment by andymartin-sch** [comment]
Ah, I totally agree. I actually hadn't tried clicking the "Sign Up via GitHub" button at all and didn't notice that it's already set up to do the register_token-ing.

**Comment by maiamcc** [comment]
Have clarified the copy a bit, hope that helps! We're still working on improving this flow, but at the very least things shouldn't be _actively confusing_ now.
