### ISSUE TITLE
Godoc link in readme broken

### ISSUE THREAD

**Issue by phroggyy** [windmilleng/tilt#3309]
Hopefully a quick and easy fix: the godoc link in the readme.md is broken:

https://godoc.org/github.com/windmilleng/tilt

Note that there's a new location which we could use: https://pkg.go.dev/github.com/windmilleng/tilt

**Comment by maiamcc** [comment]
Hmm, you mean the "godoc:reference" link at the top of `README.md`? That seems to work fine, it takes me here: https://pkg.go.dev/github.com/windmilleng/tilt?tab=doc or am I misunderstanding?

**Comment by maiamcc** [comment]
OH wait I understand now, I turned on automatic redirects from godoc.org -> pkg.go.dev. Will go fix :)
