### ISSUE TITLE
Perma-pending resource when using Kafka CRD (b/c of CRD race condition?)

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#3325]
### Problem

Got report of a CRD use case where the custom resource was stuck in "pending" forever, even though apparently all of its pods were ready. See [Tiltfile for repro](https://gist.github.com/maiamcc/4336a0ef15ff3cb77faa2cdeb6872d5c), provided by @jfancher.

Repro steps:
1. `curl https://gist.githubusercontent.com/maiamcc/4336a0ef15ff3cb77faa2cdeb6872d5c/raw/d12b22875d6d3689de74bae39b2927bc0f391482/CRD-race-condition-repro.Tiltfile > Tiltfile`
2. `tilt up`, wait for things to spin up
3. `cluster` resource will remain pending, even though according to `kubectl -n kafka get pods`, it has created multiple pods (`cluster-kafka-0`, `cluster-zookeeper-[0-2]`) and all are Running)
4. ctrl+c to exit Tilt, and `tilt up` again; this time, `cluster` eventually goes green (as does its dependent resource, `busybox`)

Expected: `cluster` and `busybox` go green on the first `tilt up`

### Investigation so far
* when `cluster` is stuck in pending, it's because Tilt doesn't know about any of its pods
* in Tilt runs where `cluster` doesn't come up, we see a lot of log spam of:
    > Handling pod update (“cluster-zookeeper-0”): error mapping kafka.strimzi.io/Kafka: no matches for kind “Kafka” in group “kafka.strimzi.io”.

    The above error [is thrown here](https://github.com/windmilleng/tilt/blob/ffd13d6b89bc49f34c083b3baa889e942f04b06a/internal/k8s/client.go#L396), when the Dynamic REST Mapper fails to look up an object by group+kind.
* here's the call chain when we get an error for the one of the problematic pods:
    ```
    goroutine 2918 [running]:
    github.com/windmilleng/tilt/internal/k8s.K8sClient.GetByReference(0x5e5deb9, 0x12, 0x62085e0, 0xc00072f900, 0x6285ec0, 0xc000200460, 0xc0004c4600, 0x61e7fc0, 0xc00072e880, 0x5e4a657, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/client.go:396 +0x519
    github.com/windmilleng/tilt/internal/k8s.OwnerFetcher.ownersOfMeta(0x6283620, 0xc0005d61e0, 0xc00025a870, 0xc0001a9688, 0x6242f20, 0xc0010c2a80, 0x6258de0, 0xc000010758, 0x0, 0x0, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/owner_fetcher.go:149 +0x298
    github.com/windmilleng/tilt/internal/k8s.OwnerFetcher.ownerTreeOfHelper(0x6283620, 0xc0005d61e0, 0xc00025a870, 0xc0001a9688, 0x6242f20, 0xc0010c2a80, 0xc001478230, 0xb, 0xc001478279, 0x5, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/owner_fetcher.go:130 +0x112
    github.com/windmilleng/tilt/internal/k8s.OwnerFetcher.OwnerTreeOf(0x6283620, 0xc0005d61e0, 0xc00025a870, 0xc0001a9688, 0x6242f20, 0xc0010c2a80, 0x62032e0, 0xc000010758, 0x0, 0x0, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/owner_fetcher.go:125 +0x236
    github.com/windmilleng/tilt/internal/k8s.OwnerFetcher.ownerTreeOfHelper(0x6283620, 0xc0005d61e0, 0xc00025a870, 0xc0001a9688, 0x6242f20, 0xc0010c2a80, 0x58a3dab, 0x3, 0xc00151d3f9, 0x5, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/owner_fetcher.go:135 +0x1c3
    github.com/windmilleng/tilt/internal/k8s.OwnerFetcher.OwnerTreeOf(0x6283620, 0xc0005d61e0, 0xc00025a870, 0xc0001a9688, 0x6242f20, 0xc0010c2a80, 0x6201120, 0xc000807400, 0x0, 0x0, ...)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/k8s/owner_fetcher.go:125 +0x236
    github.com/windmilleng/tilt/internal/engine/k8swatch.(*PodWatcher).dispatchPodChange(0xc000730a80, 0x6242f20, 0xc0010c2a80, 0xc000807400, 0x6243720, 0xc0000ce0a0)
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/engine/k8swatch/pod_watch.go:257 +0xad
    created by github.com/windmilleng/tilt/internal/engine/k8swatch.(*PodWatcher).dispatchPodChangesLoop
	    /Users/maia/code/go/src/github.com/windmilleng/tilt/internal/engine/k8swatch/pod_watch.go:291 +0x1a4
    ```

### Possible workarounds
* brute force: add a timeout (by means of a `local_resource`?) after `uncategorized` applies, to give the CRD time to be... discoverable?? Properly mapped?? This seems to work at least sometimes 😬
```
local_resource('sleep', 'sleep 15', resource_deps=["uncategorized"])
...
k8s_resource("strimzi-cluster-operator", resource_deps=["sleep"])
```
* find a way to actually check if the CRD is ready/discoverable/whatever:
```
local_resource('check-crd', '...wait for crd to be mapped...', resource_deps=["uncategorized"])
...
k8s_resource("strimzi-cluster-operator", resource_deps=["check-crd"])
```
* something else?

**Comment by nicks** [comment]
good investigation!

If the the pod watcher sees a pod, and it doesn't know the type of that pod's parent CRD, then it seems like we can safely assume that the CRD is ready. (since the CRD controller is what created the pod in the first place!) Can we just reset the REST mapper and retry?
