### ISSUE TITLE
Tilt Python example results in alert

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3327]
As reported in Slack: https://kubernetes.slack.com/archives/CESBL84MV/p1589279792026400

I (Victor) also reproduced: 

Run `tilt up` in https://github.com/windmilleng/tilt-example-python/tree/master/3-recommended

<img width="1597" alt="Screen Shot 2020-05-12 at 8 02 18 AM" src="https://user-images.githubusercontent.com/10860550/81687224-ecc19880-9426-11ea-83a4-0b8da2b9da0c.png">

**Comment by victorwuky** [comment]
I am using Python 2.7.16.

**Comment by firemanxbr** [comment]
I was checking what is the root cause of this issue, that looks like the **date** command on macOS that is different than **Linux**, for example:

```
/etc # date +%s
1589285285

/etc # date +%s%N
1589285289

/etc # cat /etc/alpine-release 
3.11.6
```

but on **macOs** we have this behavior:
```
$ date +%s
1589285475

$ date +%s%N
1589285480N 
```

Line that generates it: https://github.com/windmilleng/tilt-example-python/blob/master/3-recommended/Tiltfile#L12

**Comment by victorwuky** [comment]
Thanks @firemanxbr for finding the problem.

@maiamcc : FYI if this can be fixed quickly. Otherwise, I can link to this bug in the repo as a known bug.

**Comment by nicks** [comment]
ya, it's a BSD date vs GNU date problem -- i suspect all the Tilt engineers have GNU coreutils installed on mac, and so get the GNU date

Let me take care of this, since I have to go thru all the examples and update them for windows anyway

**Comment by victorwuky** [comment]
Thanks @nicks

**Comment by victorwuky** [comment]
Thanks @nicks . @firemanxbr : This is now fixed. Thanks for catching this issue.
