### ISSUE TITLE
Dockerfile with FROM ${SOME_ARG} fails with private registry

### ISSUE THREAD

**Issue by bkcsfi** [windmilleng/tilt#3331]
v0.13.4, built 2020-04-30

I have a tiltfile that builds multiple images from one base image.

The tiltfile also sets  a default_registry value.

Using the dockerfiles directly w/o alteration results in the following error:

```
Beginning Tiltfile execution
Image not used in any deploy config:
    ✕ python2-base
Did you mean…
    - sfi-base
    - jacobalberty/firebird
Skipping this image build
```
Example resource build error shows that its not using the private registry

```
tidy-orgs-job │      ERROR IN: [internal] load metadata for docker.io/library/python2-base:latest                                                                                             
tidy-orgs-job │      [stage-0 1/7] FROM docker.io/library/python2-base:latest                                                                                                                 
tidy-orgs-job │                                                                                                                                                                               
tidy-orgs-job │      ERROR IN: [stage-0 1/7] FROM docker.io/library/python2-base:latest                                                                                                       
tidy-orgs-job │                                                                                                                                                                               
tidy-orgs-job │ ERROR: Build Failed: ImageBuild: failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: 
 failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 
```

Here's the FROM statements used by the various docker files

* docker/Dockerfile-python2-base - FROM ubuntu
* docker/Dockerfile-sfi-base - FROM ${PYTHON2_BASE}
* docker/Dockerfile-tidy-orgs - FROM ${SFI_BASE}
* docker/Dockerfile-zeo-server - FROM ${SFI_BASE}
* docker/Dockerfile-zope-server - FROM ${SFI_BASE}
* docker/Dockerfile-zope-server-production - FROM ${ZOPE_SERVER}
* docker/Dockerfile-zope-server-deployment - FROM ${ZOPE_SERVER_PRODUCTION}
* docker/Dockerfile-zope-sync - FROM ${SFI_BASE}

To get these docker files to work, I have to rewrite them to replace  ${SOME_ARG} with their 'default' values.

I've attached a sample 'working' and non-working Tiltfile and some dump outputs.

[tiltfiles.zip](https://github.com/windmilleng/tilt/files/4619760/tiltfiles.zip)

Note, if you run tilt with `--host` option, then `tilt dump` fails to connect to it because dump doesn't appear to accept `--host` as an option.  It defaults to 127.0.0.1 which then fails

**Comment by victorwuky** [comment]
Thanks @bkcsfi for logging this.

**Comment by maiamcc** [comment]
cc @nicks, I believe you folks were talking about this earier

**Comment by nicks** [comment]
I filed a separate ticket for the --host issue: https://github.com/windmilleng/tilt/issues/3332

Thank you for the detailed report, I'll try to dig into it later this afternoon

**Comment by nicks** [comment]
This was an interesting bug, thank you!

Here's a minimal Dockerfile to repro the problem

```
# syntax=docker/dockerfile:experimental

ARG PYTHON2_BASE="python2-base"
FROM ${PYTHON2_BASE}

RUN --mount=type=cache,id=pip,target=/root/.cache/pip pip install python-dateutil
```

The --mount call is essential, but I don't totally understand yet why

**Comment by victorwuky** [comment]
@bkcsfi : This fix is now deployed with the latest release: https://github.com/tilt-dev/tilt/releases/tag/v0.13.6

**Comment by bkcsfi** [comment]
thanks, v0.13.6 works for me
