### ISSUE TITLE
Please add instructions or code modifications for exposing port on macOS

### ISSUE THREAD

**Issue by moltar** [windmilleng/tilt#857]
In your `oneup` tutorial, the Go code opens up a port, and `tilt` does report that something is running on a port:

> oneup       ┊ 2018/12/19 06:57:45 Serving oneup on 8000

However, it is not available on `localhost:8000`.

Thanks.

**Comment by jazzdan** [comment]
Hi @moltar, thanks for checking out Tilt.

The message you're seeing in the log pane is a message from the oneup service itself, thus the `oneup ┊` prefix. You can see where that log gets printed [in the oneup code](https://github.com/windmilleng/tilt/blob/master/integration/oneup/main.go#L14). So while the oneup service is listening on port 8000 that doesn't get exposed to the host machine by default.

If you wanted to expose that port on your host machine you could do that by passing the [`port_forwards` parameter](https://docs.tilt.build/api.html#api.k8s_resource) to the `k8s_resource` function in the Tiltfile. That would look something like this:

```python
docker_build('gcr.io/windmill-test-containers/integration/oneup', '.')
k8s_resource('oneup', 'oneup.yaml', port_forwards=8000)
```

**Comment by moltar** [comment]
@jazzdan Thank you for the explanation. I did realize that the message is from the Go code itself, which is behind the K8S setup.

I was commenting on the fact that your demo/getting started was incomplete (IMO) without the ability to actually access that port from the host OS.

My thinking was for 2 reasons:

1. As a user, I wanted to verify that it did in fact work and I can in fact access the server.
2. I wanted to see some log output in the log view (maybe access log or something like that). Otherwise I was not able to demo how the actual log screen worked.

Thank you for addressing it so quickly. Very impressive :)

**Comment by jazzdan** [comment]
Thanks for the feedback @moltar! That makes a lot of sense. We agree with you and now the getting started docs include accessing that service from the host. :)

> Would be cool to see some log output on the log screen for each request.

Oooh I like that, I think it would really help convey the "liveness" of Tilt.
