### ISSUE TITLE
k8s_yaml documented as expecting a string, but does not accept a string

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#894]
https://docs.tilt.build/api.html#api.k8s_yaml

this doc says that you should be able to pass in a string of yaml, but this does not actually work. it only accepts a file path or a blob.

not sure if the API should be changed to accept a string, or if there should be some other function that parses a string into a form that k8s_yaml recognizes

**Comment by jazzdan** [comment]
I addressed part of this in https://github.com/windmilleng/tilt/commit/211eb0c4a6a607f9a172726834d90b593fd997da

**Comment by jazzdan** [comment]
And the other part is now merged.

Now you can pass arbitrary YAML in to a `k8s_yaml` using the new [`yaml`](https://docs.tilt.build/api.html#api.yaml) call like so:

```python
deployment = '''
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sancho
  namespace: sancho-ns
  labels:
    app: sancho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sancho
  template:
    metadata:
      labels:
        app: sancho
    spec:
      containers:
      - name: sancho
        image: gcr.io/some-project-162817/sancho
        env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: slacktoken
                key: token
      - name: sancho-sidecar
        image: gcr.io/some-project-162817/sancho-sidecar'''
k8s_yaml(yaml(deployment)
```

**Comment by BladeMcCool** [comment]
idk the history but currently there is no "yaml" function but there is a "blob" function that fixed my problem.

# Step 1: Define the namespace manifest for 'cool-namespace'
namespace_yaml = """
apiVersion: v1
kind: Namespace
metadata:
  name: cool-namespace
"""

# Step 2: Load the namespace YAML into Tilt
k8s_yaml(blob(namespace_yaml)) #works (didnt work without wrapping the namespace_yaml in some func, tried 'yaml' like in this thread, tilt said it didnt know what it was, additional research found some post mention 'blob')
