### ISSUE TITLE
Question. Helm integration ?

### ISSUE THREAD

**Issue by sneerin** [windmilleng/tilt#928]
Is there any example that integrates with helm ?

**Comment by VivekNair** [comment]
+1 for Helm, currently the local development process with minikube and Helm is a laborious process. Tilt integration would be great.

**Comment by VivekNair** [comment]
Works for me!!

**Comment by stevenklar** [comment]
A native helm integration would be awesome. Good job. This project rocks.

But for now the above "helper" command works for me as well. :-)

**Comment by thedrow** [comment]
Also, some people use https://github.com/roboll/helmfile for deploying everything with helm.
It's something you should keep in mind.

**Comment by jazzdan** [comment]
Hey all,

The [v0.5.0](https://github.com/windmilleng/tilt/releases/tag/v0.5.0) release contains a built-in `helm` command that does exactly what @nicks' snippet does. It also has [API docs](). Here's a quick example of its use in a Tiltfile

```python
yml = helm('chartdir')
k8s_yaml(yml)
```

Let me know if you have any questions! I'm going to close this issue in the meantime.
