### ISSUE TITLE
`terminal entry not found` on macOS

### ISSUE THREAD

**Issue by johnboiles** [windmilleng/tilt#942]
Just downloaded tilt via the instructions and attempted to run the example program.

```bash
> curl -L https://github.com/windmilleng/tilt/releases/download/v.4.1/tilt.0.4.1.mac.x86_64.tar.gz | tar -xzv tilt && sudo mv tilt /usr/local/bin/tilt
... curl stuff ...
> git clone https://github.com/windmilleng/tilt
... git stuff ...
> tilt version
Send anonymized usage data to Windmill [y/n]? y
Thanks! Setting 'tilt analytics opt in'
You set can update your privacy preferences later with 'tilt analytics'
v0.4.1, built 2019-01-07
> cd tilt/integration/oneup
> tilt up
Error: error initializing renderer: terminal entry not found
> echo $TERM
xterm-color
```

I'm using iTerm2 as my terminal, but I get the same results in the built-in Terminal.app.

What should I check?

**Comment by johnboiles** [comment]
Ok removed my line from my (probably ancient) `.bash_profile`

```
export TERM=xterm-color
```

And now 

```
> echo $TERM
xterm-256color
```

And everything works! I found [this SO post](https://stackoverflow.com/questions/10003136/what-is-the-difference-between-xterm-color-xterm-256color) to be an interesting read for context.

**Comment by nicks** [comment]
Thanks for the report! Even though you were able to work-around this, we should handle this more gracefully anyway, and/or give a better error message.

**Comment by nicks** [comment]
This bug ended up being far more interesting than I ever expected. The upstream terminal library we use has a very large database of popular TERM values, and managing them all is a complex engineering problem in itself.

**Comment by nicks** [comment]
in any case, the error message now reads:

```
$ TERM=xterm-color tilt up
Error: setting up screen: Tilt does not support TERM="xterm-color". This is not a common Terminal config. If you expect that you're using a common terminal, you might have misconfigured $TERM in your .profile.
```

https://github.com/windmilleng/tilt/pull/1042

so i'm going to close this as resolved
