### ISSUE TITLE
Cursor Flickering / High CPU Usage

### ISSUE THREAD

**Issue by dougsparling** [windmilleng/tilt#943]
Hey, found your cool project via HN and decided to run through the getting started guide, but immediately ran into a couple deal-breaking issues that I assume are related to each other:

Sometimes while running (idle or otherwise), tilt seems to consume about 75-150 %CPU as reported by top, and on top of that causes my terminal to eat another 75%, and if inside tmux, another 75% for the tmux server! That's quite a bit for a single tool sitting in an idle state. 

In addition, when running in tmux, my cursors in other panes seem to flicker rapidly at the same time of the CPU usage spikes, suggesting the cause might be unnecessarily frequent repainting by tilt.

Not sure what info would be helpful, but I'm running tilt version `v0.4.1, built 2019-01-07`, Ubuntu 18.10, tmux 2.7 and GNOME Terminal 3.33.1.

**Comment by jazzdan** [comment]
I can't repro the doubling under tmux on macOS, however.

**Comment by dougsparling** [comment]
Just to be clear, I meant that the tmux process itself also consumes excessive CPU, not that it seems to have any kind of multiplicative effect on the usage of tilt or my terminal.

Here's a snippet from top:

```
  PID USER  PR  NI    VIRT    RES    SHR S  %CPU  %MEM     
24195 doug  20   0  141.6m  75.6m  25.7m S 133.9   0.2   0:43.16 tlt                                                                                                                                                                                                                                             
 6683 doug  20   0   54.4m  37.1m   2.8m R  73.4   0.1   8:06.21 tmux: server                                                                                                                                                                                                                                    
...
 6068 doug  20   0  792.8m  44.3m  28.3m S  17.6   0.1   6:29.85 gnome-terminal
```

**Comment by jazzdan** [comment]
Aha! That makes sense, thanks for the clarification @dougsparling.

**Comment by landism** [comment]
I've added profiling to tilt with #950 and checked it out in pprof:
```
(pprof) top20 -cum
Showing nodes accounting for 1990ms, 69.82% of 2850ms total
Dropped 46 nodes (cum <= 14.25ms)
Showing top 20 nodes out of 105
      flat  flat%   sum%        cum   cum%
         0     0%     0%     2630ms 92.28%  github.com/windmilleng/tilt/internal/hud.(*Hud).Update
         0     0%     0%     2630ms 92.28%  github.com/windmilleng/tilt/internal/hud.(*Hud).refresh
         0     0%     0%     2630ms 92.28%  github.com/windmilleng/tilt/internal/hud.(*Renderer).Render
         0     0%     0%     2600ms 91.23%  github.com/windmilleng/tilt/internal/cli.(*upCmd).run.func1
         0     0%     0%     2600ms 91.23%  github.com/windmilleng/tilt/internal/hud.(*Hud).Run
         0     0%     0%     2600ms 91.23%  github.com/windmilleng/tilt/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
         0     0%     0%     2580ms 90.53%  github.com/windmilleng/tilt/internal/hud.(*Hud).Refresh
         0     0%     0%     2540ms 89.12%  github.com/windmilleng/tilt/internal/rty.(*rty).Render
         0     0%     0%     2310ms 81.05%  github.com/windmilleng/tilt/vendor/github.com/gdamore/tcell.(*tScreen).Show
         0     0%     0%     2020ms 70.88%  github.com/windmilleng/tilt/vendor/github.com/gdamore/tcell.(*tScreen).draw
         0     0%     0%     2020ms 70.88%  github.com/windmilleng/tilt/vendor/github.com/gdamore/tcell.(*tScreen).drawCell
         0     0%     0%     2020ms 70.88%  io.WriteString
         0     0%     0%     2010ms 70.53%  internal/poll.(*FD).Write
         0     0%     0%     2010ms 70.53%  os.(*File).Write
         0     0%     0%     2010ms 70.53%  os.(*File).WriteString
         0     0%     0%     2010ms 70.53%  os.(*File).write
    1990ms 69.82% 69.82%     1990ms 69.82%  syscall.Syscall
         0     0% 69.82%     1990ms 69.82%  syscall.Write
         0     0% 69.82%     1990ms 69.82%  syscall.write
         0     0% 69.82%      290ms 10.18%  github.com/windmilleng/tilt/vendor/github.com/gdamore/tcell.(*tScreen).getWinSize
```

It looks like either we're drawing much too frequently, or drawing is significantly more expensive than one might expect. I'll keep digging.

**Comment by jazzdan** [comment]
Hey @dougsparling this should be fixed as of the most recent release (https://github.com/windmilleng/tilt/releases/tag/v0.4.2), let us know if it isn't.

Thanks for the report!

**Comment by landism** [comment]
#955 made one case a lot better for me.

I'm now running a project with a ~10 minute build, and tilt is now up to 110% CPU.

For 8.5s of CPU time, a profile shows:
4.85s in `stringBuilder.Text`
1.28s in `Tokenizer.Next`
.9s in runtime gcDrain
.43 in mallocgc
