### ISSUE TITLE
"First Tilt Project" doc requires user troubleshooting

### ISSUE THREAD

**Issue by smena** [windmilleng/tilt#966]
Mac OS 10.13.3 (17D47)
go version go1.11.1 darwin/amd64
Docker version: 18.09.0, API version: 1.39

New Mac users following the [first example guide](https://docs.tilt.build/first_example.html) will encounter issues requiring some troubleshooting:

- If the user opted for the curl method of installing Tilt in the [Tilt installation guide](https://docs.tilt.build/install.html), the "tilt up" command on the first example guide throws an error:

`       ERROR: ImageBuild: failed to create LLB definition: Dockerfile parse error line 1: unknown            instruction:                                                                                          PAXHEADERS.0                                                                                                0000000 0000000 0000000 00000000044 00000000000 010142`

However, `docker build .` on the Dockerfile present in `tilt/integration/oneup` successfully builds the image. Using the `go get` method of installing Tilt allows you to successfully build the image with `tilt up`.

- Once the image is built, it attempts to push an image to GCR to which the user may not have access by default.

`ERROR: pushing image "gcr.io/windmill-test-containers/integration/oneup": unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication`

A Google account is not listed as a prerequisite. Even if it were, new users should not be pushing to a shared registry. To get past this error, the user must:

1. Go to https://console.cloud.google.com/gcr/images/windmill-test-containers/ and log in with Google credentials to obtain the pull command/tag ID from the most recent push (because there is no "latest" tag)
2. Pull the image down
3. Tag the pulled image in order to push it to their container registry of choice
4. Update the Tiltfile to reflect the new image location
5. Update the oneup.yaml to reflect the new image location

Then `tilt up` is successful and the user can proceed.

**Comment by nicks** [comment]
Thanks for the report!

The first issue should be fixed in Tilt v0.4.2, which released today. I suspect that you just barely missed the update! :sweat_smile: 

The second issue sounds like you are trying to use a remote cluster rather than a local cluster. We should add some instructions that fail if you try to use a remote cluster.

Can you run

```
kubectl config current-context
```

to confirm this is the case?

**Comment by smena** [comment]
` ~ $ kubectl config current-context
docker-for-desktop`

The image push to GCR seems to happen because that is the path to the image as configured in oneup.yaml and the Tiltfile. The instructions point you to the example project at `https://github.com/windmilleng/tilt.git`.

**Comment by ahopkins** [comment]
I can report that this is not a Mac related issue. I am trying to follow the tutorial as well, and would like to avoid having to add any Google credentials. I guess I am not sure why I am even trying to push anything anyway? I guess I will clone the repo and push it somewhere else and change the yaml as suggested above.

I suggest fixing the tutorial to be more clear.

**Comment by ahopkins** [comment]
I made a copy of the repo on my [docker hub profile](https://cloud.docker.com/u/admhpkns/repository/docker/admhpkns/tilt-oneup-test).

Then changed `oneup.yml` and the `Tiltfile` to `admhpkns/tilt-oneup-test`.

```
  RESOURCE NAME                                                                                            K8S •    BUILD STATUS •  UPDATED 
▼ ● oneup ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ Pending • Error    (8.6s) •        - 
    HISTORY: FIRST BUILD                                                                                         Error    (8.6s) •  <1m ago 
    ERROR:                                                                                                                                  
       ERROR: pushing image "docker.io/admhpkns/tilt-oneup-test": errors:                                                                   
       denied: requested access to the resource is denied                                                                                   
       unauthorized: authentication required  ```

**Comment by nicks** [comment]
@smena re: "The image push to GCR seems to happen because that is the path to the image as configured in oneup.yaml and the Tiltfile." I can see why you think that! That would be the naive way to implement it.

But Tilt should detect when you're using minikube or docker-for-desktop and skip the push step. Instead, it sends the image directly to the docker server in the cluster, so that it's fast enough for local dev. There's a longer technical write-up of a lot of the local build tricks we use here:

https://medium.com/windmill-engineering/how-tilt-updates-kubernetes-in-seconds-not-minutes-28ddffe2d79f

We need to figure out what's different about your machine that's making it think it needs to do a push! Let me dig around a bit. I'll get back to you later today.

@ahopkins are you also certain that your kubectl is configured for minikube or docker-for-desktop?

**Comment by smena** [comment]
After updating to the latest tilt (0.4.2) and resetting the tilt repo, `tilt up` behaves as expected.

**Comment by nicks** [comment]
Good to hear! We updated the tutorial with some more setup help and troubleshooting steps
https://docs.tilt.build/first_example.html
and added a troubleshooting section to the FAQ
https://docs.tilt.build/faq.html#troubleshooting

It sounds like all the issues here are resolved, so I'm going to close this ticket, but please let us know if you have any other issues!

**Comment by generalconsensus** [comment]
Same thing happened to me one year and one day later and that first example is is a dead link

**Comment by jazzdan** [comment]
Hey @generalconsensus,

Sorry about the broken link. That should now point [here](https://docs.tilt.dev/tutorial.html).

For issues with Tilt and registries I'd recommend checking out the [personal registry guide](https://docs.tilt.dev/personal_registry.html).

If you continue to have problems please open a new issue or [get in touch with us](https://docs.tilt.dev/faq.html#q-how-do-i-get-help-with-tilt)!
