### ISSUE TITLE
Base images can't be added with docker_build

### ISSUE THREAD

**Issue by dougsparling** [windmilleng/tilt#986]
I've got a fairly ordinary deployment with an associated image, which I can add to my Tiltfile and everything works as expected.
```
k8s_yaml('uses-my-image.yaml')
docker_build('my-image', 'my-image-repo')
```

However, `my-image` is based on another image that I am actively developing. But when I try this Tiltfile:

```
k8s_yaml('uses-my-image.yaml')
docker_build('my-base-image', 'my-base-image-repo'')
docker_build('my-image', 'my-image-repo')
```

I get this error:
`image my-base-image is not used in any resource`

It would be cool if Tilt could detect that `my-image` is based on `my-base-image` via its `FROM` clause, and:
1) rebuild both images, in the correct order, when `my-base-image` changes
2) rebuild just `my-image` when only it has changed

**Comment by maiamcc** [comment]
+1 -- this came up again in a recent call (PM@PH).

**Comment by nicks** [comment]
this is in-progress!

**Comment by nicks** [comment]
This is currently checked in at master. Tilt should recognize when you have a base image in a FROM clause, and build them in the correct order.

**Comment by nicks** [comment]
(as of https://github.com/windmilleng/tilt/pull/1173)
