### ISSUE TITLE
Support building multiple images per Kubernetes object

### ISSUE THREAD

**Issue by dbentley** [windmilleng/tilt#987]
Tilt builds images and then injects them into kubernetes objects. Today, it supports only one image per kubernetes object. (This limitation came about with how we group work so we can group errors to make a more useful UX). If you have a Kubernetes object with multiple images, but Tilt only builds one, everything's fine.

Tilt should support building multiple images and injecting them into one object (e.g. a Deployment with several containers).

We're working on it, and it should be here in a bit, so this is a good issue to follow if you want it.

**Comment by jazzdan** [comment]
@nicks is this fixed now that #1019 is merged?

**Comment by nicks** [comment]
@jazzdan nope! i haven't even changed the data model yet

**Comment by nicks** [comment]
fixed in #1030
