### ISSUE TITLE
Support Tilt in CI

### ISSUE THREAD

**Issue by dbentley** [windmilleng/tilt#988]
Users want to use the same tool for local dev and CI. Using skaffold or draft supports this.

Tilt could have a mode that is meant for CI.

It actually does this today, if you run `tilt up --hud=false --watch=false`, but this doesn't give much confidence that we intend to support this.

**Comment by Raffo** [comment]
I'm strongly in favour of this. I think it would be great to see Tilt used *also* in CI. I see that Tilt could play as a nice building block for validating changes (i.e. e2e tests) against kubernetes clusters. 
From what I understand, Tilt wouldn't need big changes with respect to what it is supported today even though it isn't the nicest experience to have to explicitly setup the dependencies in a Tiltfile manually instead of having something like a "sequential", optional way of defining how and when the resources will be invoked. I'm thinking this especially regarding running the end to end tests after the setup.

**Comment by nicks** [comment]
It sounds like what you want is a "blessed" way to run Tilt with CI and control the exit code.

Would it resolve this issue if we had a 

```
tilt ci
```

command that was basically equivalent to `tilt up --hud=false --watch=false`, and exited with the exit codes of any Jobs run to completion?

**Comment by Raffo** [comment]
@nicks Yes that would be great! Part of this was also mentioned in #2794 . 

Even better, but that could be considered a further improvement, would be to have a way to manually influence the exit status in the Tiltfile: I'm thinking of something like calling a special function that will exit based on a condition. 

I'm happy to help with the implementation once we have an agreement and if I get some pointers of which areas of Tilt I would have to touch, haven't looked at the source code with attention yet. Of course feel free to go on if it's easier 😄

**Comment by andymartin-sch** [comment]
For CI purposes, it would also be nice if there was a way to have `docker_build` blocks apply multiple tags to the docker images that get produced (similar to how you can pass multiple `-t`s into a `docker build` execution).

For example, once `tilt up` finishes, we currently have to manually re-tag the image with `latest` and the jenkins build number before pushing the images to GCR.

**Comment by Raffo** [comment]
@dbentley would you be able to give me a couple of ideas/comments regarding how to implement what I described above? I started to have a look at tilt's code really briefly and I figured that this is not exactly trivial as there is no real support for such a flow.
I considered adding a new keyword similar to `local_resource` to just run a final step at the end, but I'm not sure about the design considerations of that.

I'm thinking of a couple of options:

- what about adding something like a "finalizer" (as mentioned above) to the code that is executed after https://github.com/windmilleng/tilt/blob/master/internal/store/store.go#L165 ?
- would about storing the result of the last command, no matter what that is, executed in a in memory store and then using it (still https://github.com/windmilleng/tilt/blob/master/internal/store/store.go#L165 probably) to return an appropriate err or not based on the the result? This probably only works with `local_resources` as well.

I'm not familiar to how tilt works internally so all of ☝️ might be just a collection of bad ideas 😄

**Comment by nicks** [comment]
Let me type a bunch of things about Tilt architecture and see if that helps.

Tilt is fundamentally a state control loop, much like Kubernetes. Everything in Tilt works like this:
- Listen for changes to the central state store
- If something we care about changes, do some work.
- When the work is finished, dispatch an action that updates the state store

The CI mode we're talking about is a significant change to that flow. You'd want a couple new state fields to represent the state of CI, and a new subscriber to listen for changes and determine exit status.

One way to model this might be:
- A boolean field IsCIMode 
- A boolean field CIModeStopped when the CI job has finished
- An int field CIModeExitCode that expresses the exit code for your CI job

And then add a subscriber like internal/engine/ci/CISubscriber that watches the state for all pods to come up and jobs to finish. If any pods timeout or jobs fail, it would dispatch an action to exit early.

Then you'd modify maybeFinished to check if CIModeStopped is set to true.

I would probably model the end-to-end tests as a local_resource with a resource_deps=[] that listed a dependency on all the "app" k8s resources. You wouldn't need to add anything to Tilt to do this.

**Comment by nicks** [comment]
Tilt v0.13.0 has a `tilt ci` command, try it out and let us know how it goes!
https://docs.tilt.dev/cli/tilt_ci.html
