### ISSUE TITLE
Support images in non-image fields in k8s yaml

### ISSUE THREAD

**Issue by dbentley** [windmilleng/tilt#989]
Some users may have yaml that includes images they want built/injected that's not in a field named image. Tilt could find these, perhaps with extra configuration.

**Comment by landism** [comment]
I've implemented this for EnvVars [here](https://github.com/windmilleng/tilt/pull/1117). I think it's not worth worrying about making this more general until we have a concrete use case.

**Comment by maiamcc** [comment]
Given support for EnvVars mentioned above, I'm closing this until someone comes up with a more concrete use case.
